### ISSUE TITLE
Trying to implement G2p, getting Resource errors.

### ISSUE THREAD

**Issue by spicytigermeat** [stakira/OpenUtau#1004]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Hello, I'm trying to implement a G2p I trained following the same setup as the G2p's already in the code and something is breaking the code. Upon opening a piano roll with the Phonemizer using the new G2p, I get "System.Resources.MissingManifestResourceException". This is also happening with every other G2p. Is there something I'm doing incorrectly when updating the Resources.resx file? I simply put the "g2p-en-arpax.zip" file in the G2p/Data folder, and drag it into Resources.resx. I then click "run custom tool" on Resources.resx, rebuild each section and run. This seems to have completely broken all G2p's in debug. Please let me know what I can do to get this fixed and get the G2p implemented!

### Explains how to reproduce the bug

1. Put new g2p zip folder (containing onnx, dict and phones) in G2p/Data
2. Drag it into Resources.resx
3. Run Custom Tool on Resources.resx
4. Rebuild OpenUtau, OpenUtau.Core, OpenUtau.Plugin.Builtin, OpenUtau.test
5. Run Debug to test Phonemizer with new G2p
6. Receive "System.Resources.MissingManifestResourceException" upon loading a track with new phonemizer.

### OS & Version

Windows 11

### Logs

System.Resources.MissingManifestResourceException
  HResult=0x80131532
  Message=Could not find the resource "G2p.Data.Resources.resources" among the resources "OpenUtau.Core.Analysis.Crepe.Resources.resources", "OpenUtau.Core.G2p.Data.Resources.resources", "OpenUtau.Core.Vogen.Data.VogenRes.resources" embedded in the assembly "OpenUtau.Core", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture)
   at OpenUtau.Core.G2p.Data.Resources.get_g2p_en_arpax() in D:\DIFFSINGER\OpenUtau\OpenUtau.Core\G2p\Data\Resources.Designer.cs:line 88
   at OpenUtau.Core.G2p.ArpaXG2p..ctor() in D:\DIFFSINGER\OpenUtau\OpenUtau.Core\G2p\ArpaXG2p.cs:line 35
   at OpenUtau.Core.DiffSinger.DiffSingerEnglishXPhonemizer.LoadBaseG2p() in D:\DIFFSINGER\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerEnglishXPhonemizer.cs:line 10
   at OpenUtau.Core.DiffSinger.DiffSingerG2pPhonemizer.LoadG2p(String rootPath) in D:\DIFFSINGER\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerG2pPhonemizer.cs:line 67
   at OpenUtau.Core.DiffSinger.DiffSingerBasePhonemizer.SetSinger(USinger singer) in D:\DIFFSINGER\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerBasePhonemizer.cs:line 46
   at OpenUtau.Api.PhonemizerRunner.Phonemize(PhonemizerRequest request) in D:\DIFFSINGER\OpenUtau\OpenUtau.Core\Api\PhonemizerRunner.cs:line 99
   at OpenUtau.Api.PhonemizerRunner.PhonemizerLoop() in D:\DIFFSINGER\OpenUtau\OpenUtau.Core\Api\PhonemizerRunner.cs:line 62
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by spicytigermeat** [comment]
Issue was figured out, line 42 or Resource.Designer.cs needs to be reverted to this after updating to solve the dependency issues: `global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenUTAU.Core.G2p.Data.Resources", typeof(Resources).Assembly);`
