### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection. 

### ISSUE THREAD

**Issue by yanamotopuu** [stakira/OpenUtau#1039]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

https://www.nicovideo.jp/watch/sm10726735

When I was copying and pasting lyrics using this plugin, openutau got an error and I couldn't open USTX.
I was translating the lyrics in Romaji into Chinese. The score layout has been corrected.

### Explains how to reproduce the bug

1. Prepare the UST and audio file and put it into openutau
2. Rewrite the UST lyrics and copy and paste them into Harmony.

[errorFile.zip](https://github.com/stakira/OpenUtau/files/14290864/errorFile.zip)

### OS & Version

Windows10

### Logs

Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at OpenUtau.Core.Ustx.UNote.Validate(ValidateOptions options, UProject project, UTrack track, UVoicePart part) in C:\projects\openutau\OpenUtau.Core\Ustx\UNote.cs:line 93
   at OpenUtau.Core.Ustx.UVoicePart.Validate(ValidateOptions options, UProject project, UTrack track) in C:\projects\openutau\OpenUtau.Core\Ustx\UPart.cs:line 105
   at OpenUtau.Core.Ustx.UProject.Validate(ValidateOptions options) in C:\projects\openutau\OpenUtau.Core\Ustx\UProject.cs:line 170
   at OpenUtau.Core.Format.Ustx.Load(String filePath) in C:\projects\openutau\OpenUtau.Core\Format\USTx.cs:line 87
   at OpenUtau.Core.Format.Formats.LoadProject(String[] files) in C:\projects\openutau\OpenUtau.Core\Format\Formats.cs:line 51
   at OpenUtau.App.ViewModels.MainWindowViewModel.OpenProject(String[] files) in C:\projects\openutau\OpenUtau\ViewModels\MainWindowViewModel.cs:line 125
   at OpenUtau.App.Views.MainWindow.Open() in C:\projects\openutau\OpenUtau\Views\MainWindow.axaml.cs:line 196

0.1.327.0

**Comment by yanamotopuu** [comment]
The original file still cannot be opened, but it returned after re-outputting it to USTX using UtaFormatix.

**Comment by yanamotopuu** [comment]
I'll close it now
