### ISSUE TITLE
Failed to render.

### ISSUE THREAD

**Issue by linen147** [stakira/OpenUtau#1064]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Failed to render.An error occurs when playing

### Explains how to reproduce the bug

An error occurs when clicking play

### OS & Version

 Windows 11

### Logs

Failed to render.
Missing input(s) for the inference session: tension, voicing

System.AggregateException: One or more errors occurred. (Missing input(s) for the inference session: tension, voicing)
 ---> System.ArgumentException: Missing input(s) for the inference session: tension, voicing
   at OpenUtau.Core.Onnx.VerifyInputNames(InferenceSession session, IEnumerable`1 inputs) in C:\projects\openutau\OpenUtau.Core\Util\Onnx.cs:line 96
   at OpenUtau.Core.DiffSinger.DsVariance.Process(RenderPhrase phrase) in C:\projects\openutau\OpenUtau.Core\DiffSinger\DiffSingerVariance.cs:line 160
   at OpenUtau.Core.DiffSinger.DiffSingerRenderer.InvokeDiffsinger(RenderPhrase phrase, Int32 depth, Int32 speedup) in C:\projects\openutau\OpenUtau.Core\DiffSinger\DiffSingerRenderer.cs:line 222
   at OpenUtau.Core.DiffSinger.DiffSingerRenderer.<>c__DisplayClass15_0.<Render>b__0() in C:\projects\openutau\OpenUtau.Core\DiffSinger\DiffSingerRenderer.cs:line 104
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

0.1.327.0

**Comment by yqzhishen** [comment]
The error message said

```text
Missing input(s) for the inference session: tension, voicing
```

Please check your dsconfig.yaml in your dsvariance folder, or use the exporter-generated one to avoid misconfiguration.
