### ISSUE TITLE
Doesn't launch on Linux

### ISSUE THREAD

**Issue by junetried** [stakira/OpenUtau#1083]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

I was prompted to update OpenUtau, so I did. Now, it crashes on startup with the following output:

```text
ALSA lib pcm_dsnoop.c:567:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2675:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2675:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2675:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
Unhandled exception. System.InvalidOperationException: Could not create glyphTypeface.
   at Avalonia.Media.Typeface.get_GlyphTypeface()
   at Avalonia.Rendering.Composition.Compositor.get_DiagnosticTextRenderer()
   at Avalonia.Rendering.Composition.Compositor.CreateCompositionTarget(Func`1 surfaces)
   at Avalonia.Rendering.Composition.CompositingRenderer..ctor(IRenderRoot root, Compositor compositor, Func`1 surfaces)
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.Window..ctor(IWindowImpl impl)
   at Avalonia.Controls.Window..ctor()
   at OpenUtau.App.Views.MainWindow..ctor() in /home/appveyor/projects/openutau/OpenUtau/Views/MainWindow.axaml.cs:line 51
   at OpenUtau.App.App.OnFrameworkInitializationCompleted() in /home/appveyor/projects/openutau/OpenUtau/App.axaml.cs:line 34
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at OpenUtau.App.Program.Main(String[] args) in /home/appveyor/projects/openutau/OpenUtau/Program.cs:line 42
Aborted (core dumped)
```

### Explains how to reproduce the bug

1. Run OpenUtau

### OS & Version

openSUSE Tumbleweed snapshot 20240111

### Logs

N/A

**Comment by junetried** [comment]
This is a regression. [Version 0.1.316](https://github.com/stakira/OpenUtau/releases/tag/build%2F0.1.316) works fine.
