### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by 767f** [stakira/OpenUtau#1098]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Failed to render.
Unable to load DLL 'worldline' or one of its dependencies: 找不到指定的模块。 (0x8007007E)

System.AggregateException: One or more errors occurred. (Unable to load DLL 'worldline' or one of its dependencies: 找不到指定的模块。 (0x8007007E))
 ---> System.DllNotFoundException: Unable to load DLL 'worldline' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
   at OpenUtau.Classic.WorldlineRenderer.<>c__DisplayClass8_0.<Render>b__0() in C:\projects\openutau\OpenUtau.Core\Classic\WorldlineRenderer.cs:line 65
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

0.1.327.0

### Explains how to reproduce the bug

解压后打开编辑时，不到十秒

### OS & Version

win 11

### Logs

Failed to render.
Unable to load DLL 'worldline' or one of its dependencies: 找不到指定的模块。 (0x8007007E)

System.AggregateException: One or more errors occurred. (Unable to load DLL 'worldline' or one of its dependencies: 找不到指定的模块。 (0x8007007E))
 ---> System.DllNotFoundException: Unable to load DLL 'worldline' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
   at OpenUtau.Classic.WorldlineRenderer.<>c__DisplayClass8_0.<Render>b__0() in C:\projects\openutau\OpenUtau.Core\Classic\WorldlineRenderer.cs:line 65
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

0.1.327.0

**Comment by 767f** [comment]
只要找个dll修复工具修复即可

**Comment by oxygen-dioxide** [comment]
请安装最新的[visual c++ 运行库](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170)
参见：https://github.com/stakira/OpenUtau/wiki/FAQ#on-windows-it-says-unable-to-load-dll-worldline-or-one-of-its-dependencies-or-dll-was-not-found

**Comment by oxygen-dioxide** [comment]
如果问题仍然出现，你也可以改用第三方exe引擎。[这个列表](https://github.com/stakira/OpenUtau/wiki/Resamplers-and-Wavtools#tested-resamplers-and-directories)整理了在openutau上经过测试的第三方引擎。
