### ISSUE TITLE
OpenUTAU crashing more often when using DiffSinger ReFlow models

### ISSUE THREAD

**Issue by ariikamusic** [stakira/OpenUtau#1114]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

After training a ReFlow model, both acoustic and variance, OpenUTAU tends to crash more often when pitch is being generated for an UST, even though it is a short part. Note that all my models, acoustic, duration and pitch are trained to the maximum amount of steps which is 160.000 steps. I have entered the log file underneath. The crashing happens on both DirectML and CPU use.

### Explains how to reproduce the bug

This is mostly for my experience when OpenUTAU is crashing. It always happens when I click the button "generate pitch", and it doesn't matter when it's a big part of a UST or a short part of a UST, it will crash when it takes too long to generate the pitch.

### OS & Version

Windows 11

### Logs

```
2024-04-24 11:24:25.187 +02:00 [INF] ExecuteCmd Edit Curve
2024-04-24 11:24:25.187 +02:00 [INF] ExecuteCmd Edit Curve
2024-04-24 11:24:25.187 +02:00 [INF] ExecuteCmd Edit Curve
2024-04-24 11:24:25.187 +02:00 [INF] ExecuteCmd Edit Curve
2024-04-24 11:24:25.187 +02:00 [INF] ExecuteCmd Edit Curve
2024-04-24 11:24:25.187 +02:00 [INF] ExecuteCmd Edit Curve
2024-04-24 11:24:25.187 +02:00 [INF] ExecuteCmd Edit Curve
2024-04-24 11:24:25.190 +02:00 [INF] undoGroup ended
2024-04-24 11:24:25.190 +02:00 [INF] SchedulePreRender
2024-04-24 11:24:25.190 +02:00 [INF] Publish notification Pre-render notification.
2024-04-24 11:24:25.214 +02:00 [ERR] Unhandled exception
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Avalonia.Controls.Presenters.PanelContainerGenerator.ClearItemsControlLogicalChildren()
   at Avalonia.Controls.Presenters.PanelContainerGenerator.OnItemsChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Controls.Utils.CollectionChangedEventManager.Entry.<Avalonia.Utilities.IWeakEventSubscriber<System.Collections.Specialized.NotifyCollectionChangedEventArgs>.OnEvent>g__Notify|6_0(INotifyCollectionChanged incc, NotifyCollectionChangedEventArgs args, WeakReference`1[] listeners)
   at Avalonia.Utilities.WeakEvent`2.Subscription.OnEvent(Object sender, TEventArgs eventArgs)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at OpenUtau.App.Views.PianoRollWindow.NotesContextMenuClosing(Object sender, CancelEventArgs args) in C:\projects\openutau\OpenUtau\Views\PianoRollWindow.axaml.cs:line 725
   at Avalonia.Controls.ContextMenu.CancelClosing()
   at Avalonia.Controls.ContextMenu.PopupClosing(Object sender, CancelEventArgs e)
   at Avalonia.Controls.Primitives.Popup.CloseCore()
   at Avalonia.Controls.Primitives.Popup.IsOpenChanged(AvaloniaPropertyChangedEventArgs`1 e)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, T value, BindingPriority priority, Boolean isOverriddenCurrentValue, Boolean isCoercedDefaultValue)
   at Avalonia.PropertyStore.ValueStore.SetLocalValue[T](StyledProperty`1 property, T value)
   at Avalonia.PropertyStore.ValueStore.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority)
   at Avalonia.AvaloniaObject.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority)
   at Avalonia.Controls.ContextMenu.Close()
   at Avalonia.Controls.Platform.DefaultMenuInteractionHandler.CloseMenu(IMenuItem item)
   at Avalonia.Controls.Platform.DefaultMenuInteractionHandler.PointerReleased(Object sender, PointerReleasedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers, IInputElement hitTest)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at OpenUtau.App.Program.Main(String[] args) in C:\projects\openutau\OpenUtau\Program.cs:line 42
```

**Comment by oxygen-dioxide** [comment]
https://github.com/stakira/OpenUtau/pull/1178 This PR may help solving your issue
