### ISSUE TITLE
Failed to render (the remix)

### ISSUE THREAD

**Issue by KittyPlayz** [stakira/OpenUtau#1133]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Whenever I press play, it immediately spits out this error code:

Failed to render.
BadDeviceId calling waveOutOpen

NAudio.MmException: BadDeviceId calling waveOutOpen
   at NAudio.MmException.Try(MmResult result, String function)
   at NAudio.Wave.WaveOutEvent.Init(IWaveProvider waveProvider)
   at NAudio.Wave.WaveExtensionMethods.Init(IWavePlayer wavePlayer, ISampleProvider sampleProvider, Boolean convertTo16Bit)
   at OpenUtau.Audio.NAudioOutput.Init(ISampleProvider sampleProvider) in C:\projects\openutau\OpenUtau.Core\Audio\NAudioOutput.cs:line 52
   at OpenUtau.Core.PlaybackManager.StartPlayback(Double startMs, MasterAdapter masterAdapter) in C:\projects\openutau\OpenUtau.Core\PlaybackManager.cs:line 114
   at OpenUtau.Core.PlaybackManager.<>c__DisplayClass24_0.<Render>b__0() in C:\projects\openutau\OpenUtau.Core\PlaybackManager.cs:line 127

0.1.327.0

I am puzzled by how to fix this as even the forked versions of this software have this issue.

### Explains how to reproduce the bug

I am unsure how to recreate this error because I have no idea what thing in particular causes this error. It could be my computer chip for all I know.

### OS & Version

Windows 11

### Logs

[log20240510.txt](https://github.com/stakira/OpenUtau/files/15279020/log20240510.txt)

**Comment by KittyPlayz** [comment]
The issue wasn’t with diffsinger, it was with my computer! I just had to plug in headphones and change the phonemes to the correct default
