### ISSUE TITLE
Reoccurring Problem - OpenUtau Crashing when Saving .ustx file with Audio.

### ISSUE THREAD

**Issue by thr0waway89** [stakira/OpenUtau#1192]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Hi, I have been a frequent user of this for 6 months now. I have never experienced any problems before two weeks ago. It began when I tried to save an .ustx file with audio, which helps me know if it sounds like the original vocals, timing and so on.

It has never done this before at all, it only crashed due to oto.ini file errors and that was when I used my first Voicebank. **It only crashes if I add an audio track.** I have tested it before without an audio track and it saved normally.

_Thanks in advance~! <3_ 

### Explains how to reproduce the bug

1. First, click on File
2. Then, click on "Import Audio..." and import the audio file _**(any will work)**_
3. After you've imported the audio, go File>Save
4. Name the save file whatever and hit save
5. The error must've occurred; the ustx file is not saved when it happens

### OS & Version

MacOS 10.15.7 with version 1.497.

### When .MP3 is used **_(Song used: PoPiPo)_**

The log was too long to submit. Basically it straight up crashed.

### When .WAV is used **_(Song used: Kagerou Daze)_**
Unknown file format

System.IO.FileFormatException: Unknown file format
   at OpenUtau.Core.Format.Formats.ReadProject(String[] files) in /Users/appveyor/projects/openutau/OpenUtau.Core/Format/Formats.cs:line 72
   at OpenUtau.Core.Format.Formats.LoadProject(String[] files) in /Users/appveyor/projects/openutau/OpenUtau.Core/Format/Formats.cs:line 82
   at OpenUtau.App.ViewModels.MainWindowViewModel.OpenProject(String[] files) in /Users/appveyor/projects/openutau/OpenUtau/ViewModels/MainWindowViewModel.cs:line 134
   at OpenUtau.App.Views.MainWindow.Open() in /Users/appveyor/projects/openutau/OpenUtau/Views/MainWindow.axaml.cs:line 229

0.1.497.0

**Comment by oxygen-dioxide** [comment]
This bug is already fixed in 0.1.501
