### ISSUE TITLE
Failed to render issue on Mac

### ISSUE THREAD

**Issue by orangelemonsunshine** [stakira/OpenUtau#1206]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

I've run into a problem using OpenUtau on my computer.

The program will work just fine until I go to hit play and render any track. The Classic renderer won't work, and neither will Worldline-R.

Attempting to render a track with Classic renderer will bring up an error box with the following:

Failed to render.
Unable to load shared library 'worldline' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libworldline, 1): image not found

System.AggregateException: One or more errors occurred. (Unable to load shared library 'worldline' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libworldline, 1): image not found)
 ---> System.DllNotFoundException: Unable to load shared library 'worldline' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libworldline, 1): image not found
   at OpenUtau.Core.Render.Worldline.Resample(IntPtr request, IntPtr& y)
   at OpenUtau.Core.Render.Worldline.Resample(ResamplerItem item) in /Users/appveyor/projects/openutau/OpenUtau.Core/Render/Worldline.cs:line 271
   at OpenUtau.Classic.WorldlineResampler.DoResamplerReturnsFile(ResamplerItem item, ILogger logger) in /Users/appveyor/projects/openutau/OpenUtau.Core/Classic/WorldlineResampler.cs:line 23
   at OpenUtau.Classic.ClassicRenderer.<>c__DisplayClass8_0.<RenderInternal>b__1(ResamplerItem item) in /Users/appveyor/projects/openutau/OpenUtau.Core/Classic/ClassicRenderer.cs:line 72
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---

0.1.327.0

I don't know what error message Worldline-R creates upon trying to render due to the fact it crashes before I can copy the error message. If needed, I can reproduce the Worldline-R crash and check the logs.

### Explains how to reproduce the bug

1. Have a voicebank on a track with renderable notes (example: Defoko on a track with a single "あ" note
2. Select either Classic or Worldline-R for renderer then hit the play button
3. Error occurs. Classic simply brings up an error dialogue while Wordline-R crashes the program immediately.

### OS & Version

macOS 10.13.6 (High Sierra), using version 0.0.791(?) of OpenUtau

### Logs

2024-07-05 19:06:33.110 -06:00 [INF] Publish notification Save project
2024-07-05 19:06:33.114 -06:00 [INF] Clearing cache...
2024-07-05 19:06:33.115 -06:00 [INF] Cache cleared.
2024-07-05 19:06:33.207 -06:00 [INF] Exiting.
2024-07-05 19:06:33.207 -06:00 [INF] Exited.
2024-07-05 19:06:45.055 -06:00 [INF] Logging initialized.
2024-07-05 19:06:45.344 -06:00 [INF] Unix 10.13.6
2024-07-05 19:06:45.350 -06:00 [INF] Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 X64 X64
2024-07-05 19:06:45.351 -06:00 [INF] OpenUtau v0.1.327.0 osx.10.13-x64
2024-07-05 19:06:45.351 -06:00 [INF] Data path = /Users/rion/Library/OpenUtau
2024-07-05 19:06:45.352 -06:00 [INF] Cache path = /Users/rion/Library/Caches/OpenUtau
2024-07-05 19:06:47.088 -06:00 [INF] Initializing application.
2024-07-05 19:06:47.818 -06:00 [INF] Initializing culture.
2024-07-05 19:06:48.421 -06:00 [INF] Initialized culture.
2024-07-05 19:06:48.421 -06:00 [INF] Initializing theme.
2024-07-05 19:06:48.476 -06:00 [INF] Initialized theme.
2024-07-05 19:06:48.487 -06:00 [INF] Initializing OpenUtau.
2024-07-05 19:06:48.499 -06:00 [INF] Searching singers.
2024-07-05 19:06:48.616 -06:00 [INF] Search all plugins: 00:00:00.0966882
2024-07-05 19:06:48.623 -06:00 [INF] Search all legacy plugins: 00:00:00.0062824
2024-07-05 19:06:48.626 -06:00 [INF] Initialized OpenUtau.
2024-07-05 19:06:48.627 -06:00 [INF] Initializing audio.
2024-07-05 19:06:48.628 -06:00 [INF] ReleaseSourceTemp /Users/rion/Library/Caches/OpenUtau
2024-07-05 19:06:48.999 -06:00 [INF] Search all singers: 00:00:00.4985991
2024-07-05 19:06:49.253 -06:00 [INF] Initialized audio.
2024-07-05 19:06:49.253 -06:00 [INF] Initialized application.
2024-07-05 19:06:49.383 -06:00 [INF] Framework initialization completed.
2024-07-05 19:06:50.364 -06:00 [INF] Creating main window.
2024-07-05 19:06:51.664 -06:00 [INF] Initialized main window component.
2024-07-05 19:06:52.551 -06:00 [INF] Main window checking Update.
2024-07-05 19:06:52.557 -06:00 [INF] Created main window.
2024-07-05 19:06:54.134 -06:00 [INF] Publish notification Load project
2024-07-05 19:07:22.734 -06:00 [ERR] Failed to select appcast to update.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OpenUtau.App.ViewModels.UpdaterViewModel.SelectRelease() in /Users/appveyor/projects/openutau/OpenUtau/ViewModels/UpdaterViewModel.cs:line 87
   at OpenUtau.App.ViewModels.UpdaterViewModel.NewUpdaterAsync() in /Users/appveyor/projects/openutau/OpenUtau/ViewModels/UpdaterViewModel.cs:line 55
2024-07-05 19:17:04.486 -06:00 [INF] Publish notification Start loading project
2024-07-05 19:17:04.666 -06:00 [INF] Merodi Ongaku Default CV UPDATE/Merodi Ongaku Append Deep
2024-07-05 19:17:04.985 -06:00 [INF] Publish notification Load project
2024-07-05 19:17:04.985 -06:00 [INF] undoGroup started
2024-07-05 19:17:04.986 -06:00 [INF] undoGroup ended
2024-07-05 19:17:04.986 -06:00 [INF] Publish notification Pre-render notification.
2024-07-05 19:17:04.986 -06:00 [INF] Publish notification Voice color remapping.
2024-07-05 19:17:05.019 -06:00 [INF] Publish notification Finish loading project
2024-07-05 19:17:05.028 -06:00 [INF] Publish notification Phonemized
2024-07-05 19:17:06.265 -06:00 [INF] StartPlayback at 00:00:00
2024-07-05 19:17:06.403 -06:00 [ERR] Failed to render.
System.AggregateException: One or more errors occurred. (Unable to load shared library 'worldline' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libworldline, 1): image not found)
 ---> System.DllNotFoundException: Unable to load shared library 'worldline' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libworldline, 1): image not found
   at OpenUtau.Core.Render.Worldline.Resample(IntPtr request, IntPtr& y)
   at OpenUtau.Core.Render.Worldline.Resample(ResamplerItem item) in /Users/appveyor/projects/openutau/OpenUtau.Core/Render/Worldline.cs:line 271
   at OpenUtau.Classic.WorldlineResampler.DoResamplerReturnsFile(ResamplerItem item, ILogger logger) in /Users/appveyor/projects/openutau/OpenUtau.Core/Classic/WorldlineResampler.cs:line 23
   at OpenUtau.Classic.ClassicRenderer.<>c__DisplayClass8_0.<RenderInternal>b__1(ResamplerItem item) in /Users/appveyor/projects/openutau/OpenUtau.Core/Classic/ClassicRenderer.cs:line 72
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
2024-07-05 19:17:06.453 -06:00 [INF] Publish notification Error message: Failed to render. System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Unable to load shared library 'worldline' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libworldline, 1): image not found)))
 ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (Unable to load shared library 'worldline' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libworldline, 1): image not found))
 ---> System.AggregateException: One or more errors occurred. (Unable to load shared library 'worldline' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libworldline, 1): image not found)
 ---> System.DllNotFoundException: Unable to load shared library 'worldline' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libworldline, 1): image not found
   at OpenUtau.Core.Render.Worldline.Resample(IntPtr request, IntPtr& y)
   at OpenUtau.Core.Render.Worldline.Resample(ResamplerItem item) in /Users/appveyor/projects/openutau/OpenUtau.Core/Render/Worldline.cs:line 271
   at OpenUtau.Classic.WorldlineResampler.DoResamplerReturnsFile(ResamplerItem item, ILogger logger) in /Users/appveyor/projects/openutau/OpenUtau.Core/Classic/WorldlineResampler.cs:line 23
   at OpenUtau.Classic.ClassicRenderer.<>c__DisplayClass8_0.<RenderInternal>b__1(ResamplerItem item) in /Users/appveyor/projects/openutau/OpenUtau.Core/Classic/ClassicRenderer.cs:line 72
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at OpenUtau.Classic.ClassicRenderer.<>c__DisplayClass8_0.<RenderInternal>b__0() in /Users/appveyor/projects/openutau/OpenUtau.Core/Classic/ClassicRenderer.cs:line 64
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at OpenUtau.Core.Render.RenderEngine.RenderRequests(RenderPartRequest[] requests, CancellationTokenSource cancellation, Boolean playing) in /Users/appveyor/projects/openutau/OpenUtau.Core/Render/RenderEngine.cs:line 221
   at OpenUtau.Core.Render.RenderEngine.<>c__DisplayClass3_0.<RenderMixdown>b__1() in /Users/appveyor/projects/openutau/OpenUtau.Core/Render/RenderEngine.cs:line 95
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

**Comment by BagelHero** [comment]
A couple of people have encountered this, but as far as I'm aware we have not found a reliable solution. On Windows, issues like this are usually solved by installing the C++ redistributable, but this is not a possibility on mac. So, for now, a workaround; you can use a classic resampler that works on mac. There are instructions for installing regular resamplers using wine + a wrapper [on the wiki](https://github.com/stakira/OpenUtau/wiki/Resamplers-and-Wavtools#macos), but Macres shouldn't need a script to work, so I would try that first: https://github.com/titinko/macres

After installing, select CLASSIC mode and use the settings cog on the track header to change the 'resampler' to macres instead of 'worldline'.

**Comment by zhouhao27** [comment]
> A couple of people have encountered this, but as far as I'm aware we have not found a reliable solution. On Windows, issues like this are usually solved by installing the C++ redistributable, but this is not a possibility on mac. So, for now, a workaround; you can use a classic resampler that works on mac. There are instructions for installing regular resamplers using wine + a wrapper [on the wiki](https://github.com/stakira/OpenUtau/wiki/Resamplers-and-Wavtools#macos), but Macres shouldn't need a script to work, so I would try that first: https://github.com/titinko/macres
> 
> After installing, select CLASSIC mode and use the settings cog on the track header to change the 'resampler' to macres instead of 'worldline'.

But where to change the Resampler in OpenUtau beta v0.1.1.549.0?
