### ISSUE TITLE
导入音源之后不出声音

### ISSUE THREAD

**Issue by 767f** [stakira/OpenUtau#1215]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

导入音源和自己编辑的ustx之后点击空格就没反应了

### Explains how to reproduce the bug

![2024-07-16 15-19-36](https://github.com/user-attachments/assets/c5cdc876-409e-4b25-bda4-cb97473e6c8a)

### OS & Version

win11

### Logs

并没有日志

**Comment by 767f** [comment]
![QQ20240717-132956](https://github.com/user-attachments/assets/74a5490f-3b85-4dd2-a854-2b6af2d9438e)
[log20240717.txt](https://github.com/user-attachments/files/16260657/log20240717.txt)

**Comment by 767f** [comment]
2024-07-17 13:27:59.122 +08:00 [INF] Logging initialized.
2024-07-17 13:27:59.158 +08:00 [INF] Microsoft Windows NT 10.0.22631.0
2024-07-17 13:27:59.160 +08:00 [INF] Microsoft Windows 10.0.22631 X64 X64
2024-07-17 13:27:59.160 +08:00 [INF] OpenUtau v0.1.429.39 win10-x64
2024-07-17 13:27:59.161 +08:00 [INF] Data path = C:\Users\32167\Desktop\OpenUtau-win-x64-0.1.429.39-DiffsingerPack
2024-07-17 13:27:59.161 +08:00 [INF] Cache path = C:\Users\32167\Desktop\OpenUtau-win-x64-0.1.429.39-DiffsingerPack\Cache
2024-07-17 13:27:59.587 +08:00 [INF] Initializing application.
2024-07-17 13:27:59.671 +08:00 [INF] Initializing culture.
2024-07-17 13:27:59.723 +08:00 [INF] Initialized culture.
2024-07-17 13:27:59.723 +08:00 [INF] Initializing theme.
2024-07-17 13:27:59.733 +08:00 [INF] Initialized theme.
2024-07-17 13:27:59.733 +08:00 [INF] Initializing OpenUtau.
2024-07-17 13:27:59.737 +08:00 [INF] Searching singers.
2024-07-17 13:27:59.754 +08:00 [INF] Search all plugins: 00:00:00.0145880
2024-07-17 13:27:59.756 +08:00 [INF] Search all legacy plugins: 00:00:00.0024809
2024-07-17 13:27:59.757 +08:00 [INF] Initialized OpenUtau.
2024-07-17 13:27:59.757 +08:00 [INF] Initializing audio.
2024-07-17 13:27:59.758 +08:00 [INF] ReleaseSourceTemp C:\Users\32167\Desktop\OpenUtau-win-x64-0.1.429.39-DiffsingerPack\Cache
2024-07-17 13:27:59.803 +08:00 [ERR] Failed to load dsconfig.yaml for 绮萱_v2.4.0 from C:\Users\32167\Desktop\OpenUtau-win-x64-0.1.429.39-DiffsingerPack\Singers\Qixuan_v2.4.0_DiffSinger_OpenUtau\dsconfig.yaml
(Line: 18, Col: 12, Idx: 456) - (Line: 18, Col: 15, Idx: 459): Exception during deserialization
2024-07-17 13:27:59.820 +08:00 [INF] Search all singers: 00:00:00.0824351
2024-07-17 13:27:59.837 +08:00 [INF] Initialized audio.
2024-07-17 13:27:59.837 +08:00 [INF] Initialized application.
2024-07-17 13:27:59.837 +08:00 [INF] Framework initialization completed.
2024-07-17 13:27:59.893 +08:00 [INF] Creating main window.
2024-07-17 13:28:00.056 +08:00 [INF] Initialized main window component.
2024-07-17 13:28:00.143 +08:00 [INF] Main window checking Update.
2024-07-17 13:28:00.144 +08:00 [INF] Created main window.
2024-07-17 13:28:00.240 +08:00 [INF] SchedulePreRender
2024-07-17 13:28:00.309 +08:00 [INF] Publish notification Load project
2024-07-17 13:28:01.112 +08:00 [ERR] Failed to select appcast to update.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at OpenUtau.App.ViewModels.UpdaterViewModel.SelectRelease() in D:\a\OpenUtau\OpenUtau\OpenUtau\ViewModels\UpdaterViewModel.cs:line 89
   at OpenUtau.App.ViewModels.UpdaterViewModel.NewUpdaterAsync() in D:\a\OpenUtau\OpenUtau\OpenUtau\ViewModels\UpdaterViewModel.cs:line 55
2024-07-17 13:28:02.872 +08:00 [INF] Publish notification Start loading project
2024-07-17 13:28:02.904 +08:00 [INF] 灰雨千_DS_CN_1.2\HaiameSen_DS_CN_1.2
2024-07-17 13:28:02.917 +08:00 [INF] SchedulePreRender
2024-07-17 13:28:02.959 +08:00 [INF] Publish notification Load project
2024-07-17 13:28:02.960 +08:00 [INF] undoGroup started
2024-07-17 13:28:02.960 +08:00 [INF] undoGroup ended
2024-07-17 13:28:02.960 +08:00 [INF] SchedulePreRender
2024-07-17 13:28:02.961 +08:00 [INF] Publish notification Pre-render notification.
2024-07-17 13:28:02.961 +08:00 [INF] Publish notification Voice color remapping.
2024-07-17 13:28:03.009 +08:00 [INF] Publish notification Finish loading project
2024-07-17 13:28:03.591 +08:00 [INF] undoGroup started
2024-07-17 13:28:03.669 +08:00 [INF] undoGroup ended
2024-07-17 13:28:03.669 +08:00 [INF] SchedulePreRender
2024-07-17 13:28:03.670 +08:00 [INF] Publish notification Pre-render notification.
2024-07-17 13:28:03.776 +08:00 [INF] undoGroup started
2024-07-17 13:28:03.792 +08:00 [INF] Publish notification Start loading pianoroll window
2024-07-17 13:28:03.836 +08:00 [INF] Publish notification Select expression dyn
2024-07-17 13:28:03.839 +08:00 [INF] Publish notification Select expression dyn
2024-07-17 13:28:03.840 +08:00 [INF] Publish notification Select expression pitd
2024-07-17 13:28:03.844 +08:00 [INF] Publish notification Select expression dyn
2024-07-17 13:28:03.844 +08:00 [INF] Publish notification Select expression clr
2024-07-17 13:28:03.846 +08:00 [INF] Publish notification Select expression dyn
2024-07-17 13:28:03.846 +08:00 [INF] Publish notification Select expression eng
2024-07-17 13:28:03.852 +08:00 [INF] Publish notification Select expression dyn
2024-07-17 13:28:03.853 +08:00 [INF] Publish notification Select expression vel
2024-07-17 13:28:03.904 +08:00 [ERR] undoGroup already started
2024-07-17 13:28:03.904 +08:00 [INF] undoGroup ended
2024-07-17 13:28:03.904 +08:00 [INF] SchedulePreRender
2024-07-17 13:28:03.904 +08:00 [INF] Publish notification Pre-render notification.
2024-07-17 13:28:03.904 +08:00 [INF] undoGroup started
2024-07-17 13:28:03.904 +08:00 [INF] undoGroup ended
2024-07-17 13:28:03.904 +08:00 [INF] SchedulePreRender
2024-07-17 13:28:03.904 +08:00 [INF] Publish notification Pre-render notification.
2024-07-17 13:28:03.906 +08:00 [INF] undoGroup started
2024-07-17 13:28:03.906 +08:00 [INF] undoGroup ended
2024-07-17 13:28:03.906 +08:00 [INF] SchedulePreRender
2024-07-17 13:28:03.906 +08:00 [INF] Publish notification Pre-render notification.
2024-07-17 13:28:04.044 +08:00 [INF] Publish notification Finish loading pianoroll window
2024-07-17 13:28:04.045 +08:00 [INF] Publish notification Select expression dyn
2024-07-17 13:28:04.046 +08:00 [INF] Publish notification Select expression pitd
2024-07-17 13:28:04.047 +08:00 [INF] Publish notification Select expression clr
2024-07-17 13:28:04.047 +08:00 [INF] Publish notification Select expression eng
2024-07-17 13:28:04.048 +08:00 [INF] Publish notification Select expression vel
2024-07-17 13:28:04.095 +08:00 [ERR] Failed to load Portrait C:\Users\32167\Desktop\OpenUtau-win-x64-0.1.429.39-DiffsingerPack\Singers\灰雨千_DS_CN_1.2\HaiameSen_DS_CN_1.2\Sen.png
System.IO.FileNotFoundException: Could not find file 'C:\Users\32167\Desktop\OpenUtau-win-x64-0.1.429.39-DiffsingerPack\Singers\灰雨千_DS_CN_1.2\HaiameSen_DS_CN_1.2\Sen.png'.
File name: 'C:\Users\32167\Desktop\OpenUtau-win-x64-0.1.429.39-DiffsingerPack\Singers\灰雨千_DS_CN_1.2\HaiameSen_DS_CN_1.2\Sen.png'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at OpenUtau.Core.DiffSinger.DiffSingerSinger.LoadPortrait() in D:\a\OpenUtau\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerSinger.cs:line 140
   at OpenUtau.App.ViewModels.NotesViewModel.<>c__DisplayClass233_0.<LoadPortrait>b__0() in D:\a\OpenUtau\OpenUtau\OpenUtau\ViewModels\NotesViewModel.cs:line 500
2024-07-17 13:28:04.112 +08:00 [INF] Publish notification Load part
2024-07-17 13:28:04.112 +08:00 [INF] Publish notification Select expression dyn
2024-07-17 13:28:04.113 +08:00 [INF] Publish notification Select expression pitd
2024-07-17 13:28:04.115 +08:00 [ERR] No active undoGroup to end.
2024-07-17 13:28:04.169 +08:00 [INF] Created bitmap 1340, 60
2024-07-17 13:28:30.149 +08:00 [INF] Autosave skipped.
2024-07-17 13:29:00.164 +08:00 [INF] Autosave skipped.
2024-07-17 13:29:30.169 +08:00 [INF] Autosave skipped.
2024-07-17 13:30:00.170 +08:00 [INF] Autosave skipped.
2024-07-17 13:30:30.176 +08:00 [INF] Autosave skipped.

**Comment by SheldonHCheers** [comment]
我也有同样的问题

**Comment by 767f** [comment]
![QQ20240803-081930](https://github.com/user-attachments/assets/3667e148-62e5-40ba-a7ef-788013150b37)
https://opensynth.miraheze.org/wiki/OpenUTAU/使用方法
