### ISSUE TITLE
Failed to search singers error

### ISSUE THREAD

**Issue by IAmALost** [stakira/OpenUtau#1219]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When trying to choose a singer or renderer, no menu opens.
![0722](https://github.com/user-attachments/assets/98e225ce-2ef6-4270-9cf1-3cf28e4a0db9)
<img width="227" alt="Screenshot 2024-07-23 at 19 08 35" src="https://github.com/user-attachments/assets/aa18dd5a-31f8-4ef6-b850-0cddd05cdf96">

### Explains how to reproduce the bug

1. Open OpenUtau
2. Open debug menu

### OS & Version

macOS Sonoma 14.5 on Apple M2

### Logs

2024-07-23 19:10:07.776 +01:00 [INF] Logging initialized.
2024-07-23 19:10:07.849 +01:00 [INF] Unix 14.5.0
2024-07-23 19:10:07.851 +01:00 [INF] Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112 X64 X64
2024-07-23 19:10:07.853 +01:00 [INF] OpenUtau v0.1.327.0 osx.14-x64
2024-07-23 19:10:07.853 +01:00 [INF] Data path = /Users/Loobs/Library/OpenUtau
2024-07-23 19:10:07.853 +01:00 [INF] Cache path = /Users/Loobs/Library/Caches/OpenUtau
2024-07-23 19:10:08.122 +01:00 [INF] Initializing application.
2024-07-23 19:10:08.267 +01:00 [INF] Initializing culture.
2024-07-23 19:10:08.442 +01:00 [INF] Initialized culture.
2024-07-23 19:10:08.443 +01:00 [INF] Initializing theme.
2024-07-23 19:10:08.467 +01:00 [INF] Initialized theme.
2024-07-23 19:10:08.467 +01:00 [INF] Initializing OpenUtau.
2024-07-23 19:10:08.472 +01:00 [INF] Searching singers.
2024-07-23 19:10:08.492 +01:00 [INF] Search all plugins: 00:00:00.0135117
2024-07-23 19:10:08.502 +01:00 [INF] Search all legacy plugins: 00:00:00.0076660
2024-07-23 19:10:08.506 +01:00 [INF] Initialized OpenUtau.
2024-07-23 19:10:08.507 +01:00 [INF] Initializing audio.
2024-07-23 19:10:08.509 +01:00 [INF] ReleaseSourceTemp /Users/Loobs/Library/Caches/OpenUtau
2024-07-23 19:10:08.608 +01:00 [INF] Initialized audio.
2024-07-23 19:10:08.608 +01:00 [INF] Initialized application.
2024-07-23 19:10:08.623 +01:00 [ERR] Avatar can't be found
2024-07-23 19:10:08.662 +01:00 [INF] Framework initialization completed.
2024-07-23 19:10:08.636 +01:00 [ERR] Failed to search singers.
System.IO.FileNotFoundException: Could not find file '/Users/Loobs/Library/OpenUtau/Singers/My Voice/dsconfig.yaml'.
File name: '/Users/Loobs/Library/OpenUtau/Singers/My Voice/dsconfig.yaml'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at OpenUtau.Core.DiffSinger.DiffSingerSinger..ctor(Voicebank voicebank) in /Users/appveyor/projects/openutau/OpenUtau.Core/DiffSinger/DiffSingerSinger.cs:line 77
   at OpenUtau.Classic.ClassicSingerLoader.AdjustSingerType(Voicebank v) in /Users/appveyor/projects/openutau/OpenUtau.Core/Classic/ClassicSingerLoader.cs:line 13
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at OpenUtau.Classic.ClassicSingerLoader.FindAllSingers() in /Users/appveyor/projects/openutau/OpenUtau.Core/Classic/ClassicSingerLoader.cs:line 26
   at OpenUtau.Core.SingerManager.SearchAllSingers() in /Users/appveyor/projects/openutau/OpenUtau.Core/SingerManager.cs:line 34
2024-07-23 19:10:08.764 +01:00 [INF] Creating main window.
2024-07-23 19:10:09.077 +01:00 [INF] Initialized main window component.
2024-07-23 19:10:09.243 +01:00 [INF] Main window checking Update.
2024-07-23 19:10:09.246 +01:00 [INF] Created main window.
2024-07-23 19:10:09.457 +01:00 [INF] SchedulePreRender
2024-07-23 19:10:09.602 +01:00 [INF] Publish notification Load project
2024-07-23 19:10:10.478 +01:00 [INF] Checking update at: https://github.com/stakira/OpenUtau/releases/tag/build/0.1.327
2024-07-23 19:10:10.480 +01:00 [INF] Checking appcast: https://github.com/stakira/OpenUtau/releases/download/build/0.1.327/appcast.osx-x64.xml

**Comment by IAmALost** [comment]
This worked thank you!
