### ISSUE TITLE
Resamplers tend to crash (Linux)

### ISSUE THREAD

**Issue by p0pnstxr** [stakira/OpenUtau#1231]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Most of the time OpenUTAU and its resamplers run ok (aside from weird UI slowness and broken plugins), but out of nowhere most of my resamplers tend to crash with no apparent reason why no matter the voicebank. I've tried switching WINE's version of Windows, changing moreconfig settings, and installing C++ libraries to the wineprefix, but nothing seems to fix it. I would appreciate help with this bug, have a nice day

### Explains how to reproduce the bug

1. Load any .ustx
2. Set Resampler to Classic ---> Moresampler (though this seems to happen with tips, tn_fnds, straycat-rs and macres)
3. Press Play button (either results in a WINE popup or an OU popup)

### OS & Version

UwUntu (Ubuntu) 22.10 LTS x86_64 (AMD)

### Logs

Moresampler example:

Failed to render

moresampler.sh failed to resample "n きB3" at 15:1.000

System.AggregateException: One or more errors occurred. (moresampler.sh failed to resample "n きB3" at 15:1.000)
 ---> System.IO.InvalidDataException: moresampler.sh failed to resample "n きB3" at 15:1.000
   at OpenUtau.Classic.ClassicRenderer.<>c__DisplayClass8_0.<RenderInternal>b__1(ResamplerItem item) in /home/appveyor/projects/openutau/OpenUtau.Core/Classic/ClassicRenderer.cs:line 83
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---

0.1.529.0

Straycat example:

Failed to render

straycat-rs.sh failed to resample "- あB3" at 0:1.000

System.AggregateException: One or more errors occurred. (straycat-rs.sh failed to resample "- あB3" at 0:1.000)
 ---> System.IO.InvalidDataException: straycat-rs.sh failed to resample "- あB3" at 0:1.000
   at OpenUtau.Classic.ClassicRenderer.<>c__DisplayClass8_0.<RenderInternal>b__1(ResamplerItem item) in /home/appveyor/projects/openutau/OpenUtau.Core/Classic/ClassicRenderer.cs:line 83
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---

0.1.529.0

Whatever this is (might be important):

ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred

**Comment by oxygen-dioxide** [comment]
This might be an issue of WINE rather than OpenUtau. You can try directly pass the command line arguments to your resampler in wine and see what happens.
