### ISSUE TITLE
Installing a Classic UTAU VB returns an `System.IO.FileNotFoundException` exception

### ISSUE THREAD

**Issue by mbekkomo** [stakira/OpenUtau#1270]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When installing a Classic UTAU VB, OpenUtau failed to install it and returns an error.
```
Failed to install singer: /home/komo/Documents/rfdel-r618.zip
The type initializer for 'SharpCompress.Common.ArchiveEncoding' threw an exception.

System.TypeInitializationException: The type initializer for 'SharpCompress.Common.ArchiveEncoding' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Text.Encoding.CodePages, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   --- End of inner exception stack trace ---
   at SharpCompress.Common.ArchiveEncoding..ctor()
   at SharpCompress.Common.OptionsBase..ctor()
   at SharpCompress.Readers.ReaderOptions..ctor()
   at SharpCompress.Archives.ArchiveFactory.Open(FileInfo fileInfo, ReaderOptions options)
   at SharpCompress.Archives.ArchiveFactory.Open(String filePath, ReaderOptions options)
   at OpenUtau.App.ViewModels.SingerSetupViewModel.IsEncrypted(String archiveFilePath) in /build/source/OpenUtau/ViewModels/SingerSetupViewModel.cs:line 99
   at OpenUtau.App.ViewModels.SingerSetupViewModel.<.ctor>b__35_1(String _) in /build/source/OpenUtau/ViewModels/SingerSetupViewModel.cs:line 49
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/DistinctUntilChanged.cs:line 72
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs:line 101
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 141
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1375
   at System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.BufferClosingObserver.OnNext(TBufferClosing value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Buffer.cs:line 827
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 238
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 141
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.NotifyObservable[T](TSender rxObj, T item, ISubject`1 subject) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 430
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.RaisePropertyChanged(String propertyName) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 395
   at ReactiveUI.IReactiveObjectExtensions.RaisingPropertyChanged[TSender](TSender reactiveObject, String propertyName) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 243
   at ReactiveUI.IReactiveObjectExtensions.RaiseAndSetIfChanged[TObj,TRet](TObj reactiveObject, TRet& backingField, TRet newValue, String propertyName) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 131
   at OpenUtau.App.ViewModels.SingerSetupViewModel.set_ArchiveFilePath(String value) in /build/source/OpenUtau/ViewModels/SingerSetupViewModel.cs:line 20
   at OpenUtau.App.Views.MainWindow.OnMenuInstallSinger(Object sender, RoutedEventArgs args) in /build/source/OpenUtau/Views/MainWindow.axaml.cs:line 599

0.1.529.0
```
Haven't tested with DS or Enunu VB.

### Explains how to reproduce the bug

1. Go to "Tools" -> "Install Singer"
2. Select a Classic UTAU VB

### OS & Version

NixOS 24.05

### Logs

```
2024-09-05 03:25:12.424 +08:00 [INF] Logging initialized.
2024-09-05 03:25:12.650 +08:00 [INF] Unix 6.6.48.0
2024-09-05 03:25:12.658 +08:00 [INF] Linux 6.6.48 #1-NixOS SMP PREEMPT_DYNAMIC Thu Aug 29 15:33:59 UTC 2024 X64 X64
2024-09-05 03:25:12.659 +08:00 [INF] OpenUtau v0.1.529.0 nixos.24.05-x64
2024-09-05 03:25:12.659 +08:00 [INF] Data path = /home/komo/.local/share/OpenUtau
2024-09-05 03:25:12.660 +08:00 [INF] Cache path = /home/komo/.cache/OpenUtau
2024-09-05 03:25:13.984 +08:00 [INF] Initializing application.
2024-09-05 03:25:14.885 +08:00 [INF] Initializing culture.
2024-09-05 03:25:15.867 +08:00 [INF] Initialized culture.
2024-09-05 03:25:15.868 +08:00 [INF] Initializing theme.
2024-09-05 03:25:16.009 +08:00 [INF] Initialized theme.
2024-09-05 03:25:16.010 +08:00 [INF] Initializing OpenUtau.
2024-09-05 03:25:16.034 +08:00 [INF] Searching singers.
2024-09-05 03:25:16.085 +08:00 [INF] Search all plugins: 00:00:00.0375359
2024-09-05 03:25:16.087 +08:00 [INF] Search all singers: 00:00:00.0510935
2024-09-05 03:25:16.092 +08:00 [INF] Search all legacy plugins: 00:00:00.0060703
2024-09-05 03:25:16.097 +08:00 [INF] Initialized OpenUtau.
2024-09-05 03:25:16.098 +08:00 [INF] Initializing audio.
2024-09-05 03:25:16.102 +08:00 [INF] ReleaseSourceTemp /home/komo/.cache/OpenUtau
2024-09-05 03:25:16.565 +08:00 [INF] Initialized audio.
2024-09-05 03:25:16.567 +08:00 [INF] Initialized application.
2024-09-05 03:25:16.570 +08:00 [INF] Framework initialization completed.
2024-09-05 03:25:16.932 +08:00 [INF] Creating main window.
2024-09-05 03:25:18.470 +08:00 [INF] Initialized main window component.
2024-09-05 03:25:18.979 +08:00 [INF] Main window checking Update.
2024-09-05 03:25:18.984 +08:00 [INF] Created main window.
2024-09-05 03:25:19.932 +08:00 [INF] SchedulePreRender
2024-09-05 03:25:20.566 +08:00 [INF] Publish notification Load project
2024-09-05 03:25:21.696 +08:00 [INF] Checking update at: https://github.com/stakira/OpenUtau/releases/tag/build/0.1.529
2024-09-05 03:25:21.703 +08:00 [INF] Checking appcast: https://github.com/stakira/OpenUtau/releases/download/build/0.1.529/appcast.linux-x64.xml
2024-09-05 03:25:29.448 +08:00 [ERR] Failed to install singer /home/komo/Documents/rfdel-r618.zip
System.TypeInitializationException: The type initializer for 'SharpCompress.Common.ArchiveEncoding' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Text.Encoding.CodePages, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   --- End of inner exception stack trace ---
   at SharpCompress.Common.ArchiveEncoding..ctor()
   at SharpCompress.Common.OptionsBase..ctor()
   at SharpCompress.Readers.ReaderOptions..ctor()
   at SharpCompress.Archives.ArchiveFactory.Open(FileInfo fileInfo, ReaderOptions options)
   at SharpCompress.Archives.ArchiveFactory.Open(String filePath, ReaderOptions options)
   at OpenUtau.App.ViewModels.SingerSetupViewModel.IsEncrypted(String archiveFilePath) in /build/source/OpenUtau/ViewModels/SingerSetupViewModel.cs:line 99
   at OpenUtau.App.ViewModels.SingerSetupViewModel.<.ctor>b__35_1(String _) in /build/source/OpenUtau/ViewModels/SingerSetupViewModel.cs:line 49
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/DistinctUntilChanged.cs:line 72
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Where.cs:line 54
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs:line 101
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.IdentitySink`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Internal/IdentitySink.cs:line 15
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Where.cs:line 54
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Cast`2._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Cast.cs:line 40
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.IdentitySink`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Internal/IdentitySink.cs:line 15
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.IdentitySink`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Internal/IdentitySink.cs:line 15
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1375
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.BufferClosingObserver.OnNext(TBufferClosing value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Buffer.cs:line 827
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 238
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Where.cs:line 54
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.NotifyObservable[T](TSender rxObj, T item, ISubject`1 subject) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 430
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.RaisePropertyChanged(String propertyName) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 395
   at ReactiveUI.IReactiveObjectExtensions.RaisingPropertyChanged[TSender](TSender reactiveObject, String propertyName) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 243
   at ReactiveUI.IReactiveObjectExtensions.RaiseAndSetIfChanged[TObj,TRet](TObj reactiveObject, TRet& backingField, TRet newValue, String propertyName) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 131
   at OpenUtau.App.ViewModels.SingerSetupViewModel.set_ArchiveFilePath(String value) in /build/source/OpenUtau/ViewModels/SingerSetupViewModel.cs:line 20
   at OpenUtau.App.Views.MainWindow.OnMenuInstallSinger(Object sender, RoutedEventArgs args) in /build/source/OpenUtau/Views/MainWindow.axaml.cs:line 599
2024-09-05 03:25:36.140 +08:00 [INF] Exiting.
2024-09-05 03:25:36.141 +08:00 [INF] Exited.
```

**Comment by r3n3gad3p3arl** [comment]
It seems like we're having the same problem (#1233). I wonder if it's a problem with the NixOS package...

**Comment by cattokomo** [comment]
> It seems like we're having the same problem (#1233). I wonder if it's a problem with the NixOS package...

This issue only appeared on the Nix package of OpenUtau, I guess it has to be related with the current .NET that nixpkgs' OpenUtau used.
