### ISSUE TITLE
Rendering broke? 

### ISSUE THREAD

**Issue by animelovrer** [stakira/OpenUtau#1313]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Ok so I was making a cover for senbonzakura and apparently the whole program glitched itself to where it won't render any tuning at all. It apparently seems to only be this file and no other for some odd reason. 
![image](https://github.com/user-attachments/assets/f68ecce7-3274-41c2-98c4-2733fb9bdd60)

I'd delete my tuning and let it render and then it just moves back further until there is no rendering on the whole file. Then I get THIS error

Failed to render

moresampler-0.8.4\moresampler.exe failed to resample "n じょ↓" at 29:1.330

System.AggregateException: One or more errors occurred. (moresampler-0.8.4\moresampler.exe failed to resample "n じょ↓" at 29:1.330)
 ---> System.IO.InvalidDataException: moresampler-0.8.4\moresampler.exe failed to resample "n じょ↓" at 29:1.330
   at OpenUtau.Classic.ClassicRenderer.<>c__DisplayClass8_0.<RenderInternal>b__1(ResamplerItem item) in C:\projects\openutau\OpenUtau.Core\Classic\ClassicRenderer.cs:line 83
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---

0.1.529.0

I've never had this issue before and I swear if my file corrupted itself after working on this for hours, I am going to cry. 

### Explains how to reproduce the bug

[11_1_2024, 9_49_14 PM - Screen - Untitled video.webm](https://github.com/user-attachments/assets/0dd371e7-536a-4cb7-8df1-f21a9f382e5a)

### OS & Version

Windows 10

### Logs

[log20241101.txt](https://github.com/user-attachments/files/17605176/log20241101.txt)
[log20241101_001.txt](https://github.com/user-attachments/files/17605177/log20241101_001.txt)
[log20241101_002.txt](https://github.com/user-attachments/files/17605179/log20241101_002.txt)

**Comment by animelovrer** [comment]
ok so it might have been my cache overloading so i cleared it and now im waiting for everything to rerender. hopefully this solves the problem
