### ISSUE TITLE
Make the Resampler Flag case sensitive

### ISSUE THREAD

**Issue by Elem-draws** [stakira/OpenUtau#1315]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Moresampler requires expressions of its own, which have to be manually added. The problem occurs when I try to add the distortion flag ("MD") after adding the dryness flag ("Md").

### Explains how to reproduce the bug

1. Open openUTAU
2. Choose singer
3. Choose Moresampler as the resampler
4. Open the track and add expressions
5. Add the dryness flag ("Md")
6. Add the distortion flag ("MD")
7. Get the error

### OS & Version

Windows 10

### Logs

An item with the same key has already been added. Key: md

System.ArgumentException: An item with the same key has already been added. Key: md
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](TSource[] source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at OpenUtau.Core.ConfigureExpressionsCommand.Execute() in C:\projects\openutau\OpenUtau.Core\Commands\ProjectCommands.cs:line 169
   at OpenUtau.Core.DocManager.ExecuteCmd(UCommand cmd) in C:\projects\openutau\OpenUtau.Core\DocManager.cs:line 244
   at OpenUtau.App.ViewModels.ExpressionsViewModel.Apply() in C:\projects\openutau\OpenUtau\ViewModels\ExpressionsViewModel.cs:line 152
   at OpenUtau.App.Views.ExpressionsDialog.ApplyButtonClicked(Object sender, RoutedEventArgs _) in C:\projects\openutau\OpenUtau\Views\ExpressionsDialog.axaml.cs:line 15

0.1.529.0

**Comment by BagelHero** [comment]
Huh, odd... well, good thing we have a workaround-- you can include manifests that allow you to use the big "load expressions from resampler" button instead so you don't need to add the expressions manually for every project.

https://github.com/stakira/OpenUtau/wiki/Resamplers-and-Wavtools#resampler-manifest

The example provided here is for moresampler (we have more premade ones available too), but importantly it seems if you use this it WILL differentiate the flags. The issue is just when adding them in-editor it seems.

**Comment by Elem-draws** [comment]
The manifest gets the job done AND saves me time on adding expressions, rather than doing manually! Thank you!
