### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by Ksauxion** [stakira/OpenUtau#1339]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Failed to render

Access to the path 'D:\utau\o2_test\configs\dsvariance' is denied.

System.AggregateException: One or more errors occurred. (Access to the path 'D:\utau\o2_test\configs\dsvariance' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'D:\utau\o2_test\configs\dsvariance' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at OpenUtau.Core.DiffSinger.DsVariance..ctor(String rootPath) in C:\Users\Ksion\Desktop\egeg\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerVariance.cs:line 67
   at OpenUtau.Core.DiffSinger.DiffSingerSinger.getVariancePredictor() in C:\Users\Ksion\Desktop\egeg\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerSinger.cs:line 204
   at OpenUtau.Core.DiffSinger.DiffSingerRenderer.InvokeDiffsinger(RenderPhrase phrase, Double depth, Int32 steps, CancellationTokenSource cancellation) in C:\Users\Ksion\Desktop\egeg\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerRenderer.cs:line 320
   at OpenUtau.Core.DiffSinger.DiffSingerRenderer.<>c__DisplayClass15_0.<Render>b__0() in C:\Users\Ksion\Desktop\egeg\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerRenderer.cs:line 106
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

0.0.0.0

### Explains how to reproduce the bug

I loaded a diffsinger voicebank. It shows me that dsvariance folder can't be accessed. 5 minutes ago it HAD access.

### OS & Version

Windows 10

### Logs

Failed to render

Access to the path 'D:\utau\o2_test\configs\dsvariance' is denied.

System.AggregateException: One or more errors occurred. (Access to the path 'D:\utau\o2_test\configs\dsvariance' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'D:\utau\o2_test\configs\dsvariance' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at OpenUtau.Core.DiffSinger.DsVariance..ctor(String rootPath) in C:\Users\Ksion\Desktop\egeg\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerVariance.cs:line 67
   at OpenUtau.Core.DiffSinger.DiffSingerSinger.getVariancePredictor() in C:\Users\Ksion\Desktop\egeg\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerSinger.cs:line 204
   at OpenUtau.Core.DiffSinger.DiffSingerRenderer.InvokeDiffsinger(RenderPhrase phrase, Double depth, Int32 steps, CancellationTokenSource cancellation) in C:\Users\Ksion\Desktop\egeg\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerRenderer.cs:line 320
   at OpenUtau.Core.DiffSinger.DiffSingerRenderer.<>c__DisplayClass15_0.<Render>b__0() in C:\Users\Ksion\Desktop\egeg\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerRenderer.cs:line 106
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

0.0.0.0

**Comment by oxygen-dioxide** [comment]
Please provide your main dsconfig.yaml and variance dsconfig.yaml

**Comment by Ksauxion** [comment]
main dsconfig.yaml:

phonemes: ../model/phonemes.json
languages: ../model/languages.json
use_lang_id: true
acoustic: ../model/acoustic.onnx
hidden_size: 256
vocoder: nsf_hifigan
speakers:
- embeds/acoustic/o2_classic
- embeds/acoustic/o2_normal
- embeds/acoustic/o2_soft
- embeds/acoustic/o2_power
- embeds/acoustic/o2_joyful
- embeds/acoustic/o2_weak

augmentation_args:
  random_pitch_shifting:
    range:
    - -5.0
    - 5.0
use_key_shift_embed: true
use_speed_embed: true
use_energy_embed: false
use_breathiness_embed: true
use_voicing_embed: true
use_tension_embed: true
use_continuous_acceleration: true
use_variable_depth: true
max_depth: 0.6
sample_rate: 44100
hop_size: 512
win_size: 2048
fft_size: 2048
num_mel_bins: 128
mel_fmin: 40
mel_fmax: 16000
mel_base: e
mel_scale: slaney


num_lang: 15
dictionaries: 
  ru: ../model/dictionary-ru.txt
  en: ../model/dictionary-en.txt
  fr: ../model/dictionary-fr.txt
  ja: ../model/dictionary-ja.txt
  ko: ../model/dictionary-ko.txt
  th: ../model/dictionary-th.txt
  zh: ../model/dictionary-zh.txt
  vi: ../model/dictionary-vi.txt
  de: ../model/dictionary-de.txt
  he: ../model/dictionary-he.txt
  pt: ../model/dictionary-pt.txt
  es: ../model/dictionary-es.txt
  uk: ../model/dictionary-uk.txt
  it: ../model/dictionary-it.txt
  ar: ../model/dictionary-ar.txt

variance dsconfig.yaml:

dur: ../../model/dur.onnx
linguistic: ../../model/linguistic.onnx
phonemes: ../../model/phonemes.json
languages: ../../model/languages.json

hop_size: 512
sample_rate: 44100

use_lang_id: true
predict_dur: true
use_expr: true
use_note_rest: false
predict_energy: false
predict_breathiness: true
predict_voicing: true
predict_tension: true
use_continuous_acceleration: true

speakers:
- ../embeds/variance/o2_classic
- ../embeds/variance/o2_normal
- ../embeds/variance/o2_soft
- ../embeds/variance/o2_power
- ../embeds/variance/o2_joyful
- ../embeds/variance/o2_weak

num_lang: 15
dictionaries: 
  ru: ../model/dictionary-ru.txt
  en: ../model/dictionary-en.txt
  fr: ../model/dictionary-fr.txt
  ja: ../model/dictionary-ja.txt
  ko: ../model/dictionary-ko.txt
  th: ../model/dictionary-th.txt
  zh: ../model/dictionary-zh.txt
  vi: ../model/dictionary-vi.txt
  de: ../model/dictionary-de.txt
  he: ../model/dictionary-he.txt
  pt: ../model/dictionary-pt.txt
  es: ../model/dictionary-es.txt
  uk: ../model/dictionary-uk.txt
  it: ../model/dictionary-it.txt
  ar: ../model/dictionary-ar.txt
