### ISSUE TITLE
Track Audio Not Playing/Not Rendering

### ISSUE THREAD

**Issue by DelphicVoiceAddragh** [stakira/OpenUtau#1350]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

For some reason, two tracks in my project suddenly aren't rendering properly after I unmuted them. OpenUTAU acts like it's rendering something (even stopping playback while waiting for a result), but there's no waveform and no audio on the affected tracks. This has persisted after changing the resampler and wavtool, clearing the cache, and restarting OpenUTAU.

The video below shows everything you need to know, but here's the file it happened in, if it helps: https://file.garden/Zu417kPYuzlvwhv4/bug%20reports/Ah%2C%20It's%20a%20Wonderful%20Cat%20Life%20-%20USTX.ustx

https://github.com/user-attachments/assets/28380faa-5f5a-4051-a08b-74200e2f770f

### Explains how to reproduce the bug

I'm completely unsure what caused it. I can only deduce that it was something that happened sometime after I deleted 2 audio file tracks.

It has nothing to do with the voicebank, as it was working fine before, and worked when I switched the voicebank on a different file.

### OS & Version

Windows 10

### Logs

[log20241204.txt](https://github.com/user-attachments/files/18003151/log20241204.txt)

**Comment by BagelHero** [comment]
How unusual. I vaguely remember the error message, but can't remember what might cause it other than another program locking up the file, which would be really strange in this case since it seems like it would be a freshly generated cache file. It works for me, for what it's worth.

```
2024-12-04 16:05:03.742 +10:30 [ERR] Failed to render: failed to open C:\Users\Administrator\Documents\OpenUtau\Cache\cat-92d8c27631a5d22c.wav
System.Exception: Unsupported audio file format.
   at OpenUtau.Core.Format.Wave.OpenFile(String filepath) in D:\a\OpenUtau\OpenUtau\OpenUtau.Core\Format\Wave.cs:line 50
   at OpenUtau.Classic.ClassicRenderer.<>c__DisplayClass9_0.<RenderExternal>b__0() in D:\a\OpenUtau\OpenUtau\OpenUtau.Core\Classic\ClassicRenderer.cs:line 107
```

I see you're using Moresampler as wavtool with Straycat-rs as resampler-- is that your go to for this vocal, and the resampler combo you used when trying the other file?

**Comment by DelphicVoiceAddragh** [comment]
I was testing various resamplers with the VB. I thought I'd had selected Moresampler for wavtool and resampler. Just tried it now and it fixed it.

Now my question is why it did that to begin with, but now I know it's probably not an OpenUTAU problem. Sorry for the trouble!
