### ISSUE TITLE
[Mac Intel] Crashes when opened / not launchable

### ISSUE THREAD

**Issue by p0pstxr** [stakira/OpenUtau#199]
### **Bug Report:**

I've installed the latest version due to my interest in it's english phonemizer and it seems to not launch, even when right-clicking. - I've tried going through the Library files and giving it an alias of my UTAU-Synth voicebank folder but it doesn't seem to read or regognize it, even when putting it as an additional singer path in it's 'path.json' file but it still doesn't launch.

### **Environment:**
 - OS: MacOS High Sierra 10.13.6 (17G14042)
 - Version 0.0.572

### **Log file:**
[name censored for personal privacy]

2021-12-09 03:56:08.601 -06:00 [ERR] Failed to save prefs.
System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/(NAME)/Library/OpenUtau/prefs.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at OpenUtau.Core.Util.Preferences.Save() in /Users/appveyor/projects/openutau/OpenUtau.Core/Util/Preferences.cs:line 19
2021-12-09 03:56:09.197 -06:00 [INF] Search all singers: 00:00:00.0040184
2021-12-09 03:56:09.206 -06:00 [INF] Search all plugins: 00:00:00.0046185
2021-12-09 03:56:09.209 -06:00 [INF] Search all legacy plugins: 00:00:00.0025563
2021-12-09 03:56:09.212 -06:00 [INF] ReleaseSourceTemp /Users/(NAME)/Library/OpenUtau/Cache
2021-12-09 03:56:09.216 -06:00 [INF] Is64BitOperatingSystem True Is64BitProcess True
2021-12-09 03:56:09.216 -06:00 [INF] Loading /Applications/OpenUtau.app/Contents/MacOS/libs/osx-x64/libportaudio.dylib
2021-12-09 03:56:09.232 -06:00 [ERR] Unhandled exception
System.Exception: Could not load libary portaudio.
   at OpenUtau.LibraryLoader..ctor(String path, String library) in /Users/appveyor/projects/openutau/OpenUtau.Core/Util/LibraryLoader.cs:line 39
   at OpenUtau.Audio.AudioOutput..ctor() in /Users/appveyor/projects/openutau/OpenUtau.Core/Audio/AudioOutput.cs:line 36
   at OpenUtau.App.Program.InitAudio() in /Users/appveyor/projects/openutau/OpenUtau/Program.cs:line 67
   at OpenUtau.App.Program.Main(String[] args) in /Users/appveyor/projects/openutau/OpenUtau/Program.cs:line 28
2021-12-09 03:56:25.423 -06:00 [INF] Search all singers: 00:00:00.0061238
2021-12-09 03:56:25.509 -06:00 [INF] Search all plugins: 00:00:00.0048104
2021-12-09 03:56:25.512 -06:00 [INF] Search all legacy plugins: 00:00:00.0027246
2021-12-09 03:56:25.515 -06:00 [INF] ReleaseSourceTemp /Users/(NAME)/Library/OpenUtau/Cache
2021-12-09 03:56:25.518 -06:00 [INF] Is64BitOperatingSystem True Is64BitProcess True
2021-12-09 03:56:25.518 -06:00 [INF] Loading /Applications/OpenUtau.app/Contents/MacOS/libs/osx-x64/libportaudio.dylib
2021-12-09 03:56:25.521 -06:00 [ERR] Unhandled exception
System.Exception: Could not load libary portaudio.
   at OpenUtau.LibraryLoader..ctor(String path, String library) in /Users/appveyor/projects/openutau/OpenUtau.Core/Util/LibraryLoader.cs:line 39
   at OpenUtau.Audio.AudioOutput..ctor() in /Users/appveyor/projects/openutau/OpenUtau.Core/Audio/AudioOutput.cs:line 36
   at OpenUtau.App.Program.InitAudio() in /Users/appveyor/projects/openutau/OpenUtau/Program.cs:line 67
   at OpenUtau.App.Program.Main(String[] args) in /Users/appveyor/projects/openutau/OpenUtau/Program.cs:line 28
2021-12-09 03:57:59.084 -06:00 [INF] Search all singers: 00:00:00.0067097
2021-12-09 03:57:59.167 -06:00 [INF] Search all plugins: 00:00:00.0043894
2021-12-09 03:57:59.170 -06:00 [INF] Search all legacy plugins: 00:00:00.0026411
2021-12-09 03:57:59.173 -06:00 [INF] ReleaseSourceTemp /Users/(NAME)/Library/OpenUtau/Cache
2021-12-09 03:57:59.176 -06:00 [INF] Is64BitOperatingSystem True Is64BitProcess True
2021-12-09 03:57:59.176 -06:00 [INF] Loading /Applications/OpenUtau.app/Contents/MacOS/libs/osx-x64/libportaudio.dylib
2021-12-09 03:57:59.179 -06:00 [ERR] Unhandled exception
System.Exception: Could not load libary portaudio.
   at OpenUtau.LibraryLoader..ctor(String path, String library) in /Users/appveyor/projects/openutau/OpenUtau.Core/Util/LibraryLoader.cs:line 39
   at OpenUtau.Audio.AudioOutput..ctor() in /Users/appveyor/projects/openutau/OpenUtau.Core/Audio/AudioOutput.cs:line 36
   at OpenUtau.App.Program.InitAudio() in /Users/appveyor/projects/openutau/OpenUtau/Program.cs:line 67
   at OpenUtau.App.Program.Main(String[] args) in /Users/appveyor/projects/openutau/OpenUtau/Program.cs:line 28
2021-12-09 04:03:46.667 -06:00 [INF] Search all singers: 00:00:02.6484445
2021-12-09 04:03:46.755 -06:00 [INF] Search all plugins: 00:00:00.0044578
2021-12-09 04:03:46.759 -06:00 [INF] Search all legacy plugins: 00:00:00.0007644
2021-12-09 04:03:46.762 -06:00 [INF] ReleaseSourceTemp /Users/(NAME)/Library/OpenUtau/Cache
2021-12-09 04:03:46.764 -06:00 [INF] Is64BitOperatingSystem True Is64BitProcess True
2021-12-09 04:03:46.765 -06:00 [INF] Loading /Applications/OpenUtau.app/Contents/MacOS/libs/osx-x64/libportaudio.dylib
2021-12-09 04:03:46.767 -06:00 [ERR] Unhandled exception
System.Exception: Could not load libary portaudio.
   at OpenUtau.LibraryLoader..ctor(String path, String library) in /Users/appveyor/projects/openutau/OpenUtau.Core/Util/LibraryLoader.cs:line 39
   at OpenUtau.Audio.AudioOutput..ctor() in /Users/appveyor/projects/openutau/OpenUtau.Core/Audio/AudioOutput.cs:line 36
   at OpenUtau.App.Program.InitAudio() in /Users/appveyor/projects/openutau/OpenUtau/Program.cs:line 67
   at OpenUtau.App.Program.Main(String[] args) in /Users/appveyor/projects/openutau/OpenUtau/Program.cs:line 28
2021-12-09 05:01:41.518 -06:00 [INF] Search all singers: 00:00:06.1072510
2021-12-09 05:01:41.769 -06:00 [INF] Search all plugins: 00:00:00.0061472
2021-12-09 05:01:41.770 -06:00 [INF] Search all legacy plugins: 00:00:00.0007003
2021-12-09 05:01:41.773 -06:00 [INF] ReleaseSourceTemp /Users/(NAME)/Library/OpenUtau/Cache
2021-12-09 05:01:41.776 -06:00 [INF] Is64BitOperatingSystem True Is64BitProcess True
2021-12-09 05:01:41.776 -06:00 [INF] Loading /Applications/OpenUtau.app/Contents/MacOS/libs/osx-x64/libportaudio.dylib
2021-12-09 05:01:41.779 -06:00 [ERR] Unhandled exception
System.Exception: Could not load libary portaudio.
   at OpenUtau.LibraryLoader..ctor(String path, String library) in /Users/appveyor/projects/openutau/OpenUtau.Core/Util/LibraryLoader.cs:line 39
   at OpenUtau.Audio.AudioOutput..ctor() in /Users/appveyor/projects/openutau/OpenUtau.Core/Audio/AudioOutput.cs:line 36
   at OpenUtau.App.Program.InitAudio() in /Users/appveyor/projects/openutau/OpenUtau/Program.cs:line 67
   at OpenUtau.App.Program.Main(String[] args) in /Users/appveyor/projects/openutau/OpenUtau/Program.cs:line 28

**Comment by nagotown** [comment]
seems like an issue with the portaudio library and not voicebanks. multiple people have had this issue so hopefully it will be fixed soon

**Comment by p0pstxr** [comment]
Update I couldnt tell if it updated or not but I finally got it to open! I'm glad it could finally work :]

**Comment by p0pstxr** [comment]
Ok so I did get it to open but it won't play anything because it doesn't recognize any of my outputs also it lists the wavs in a weird corrrupted way despite seeming perfectly fine.
![Screen Shot 2022-01-28 at 11 15 42 PM](https://user-images.githubusercontent.com/94733919/151648449-b30f5410-2971-465a-a89c-b0989359690c.png)
![Screen Shot 2022-01-28 at 11 15 11 PM](https://user-images.githubusercontent.com/94733919/151648459-cda2fc84-5967-4ea4-a8fc-dc9a33284e6e.png)
![Screen Shot 2022-01-28 at 11 15 29 PM](https://user-images.githubusercontent.com/94733919/151648464-5195a0e6-817b-490c-9fcb-b6b7d27544cf.png)

**Comment by p0pstxr** [comment]
the resampler seems to act like it works but doesnt play or even move a cent of the play line
