### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by Battle420** [stakira/OpenUtau#222]
On Linux, when executing `./OpenUtau-prerelease-x86_64.AppImage` to start the program, the following is displayed on the terminal and the app doesn't launch:

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
   at OpenUtau.LibraryLoader.dlopen(String fileName, Int32 flags)
   at OpenUtau.LibraryLoader..ctor(String path, String library) in /media/sf_Code/OpenUtau/OpenUtau.Core/Util/LibraryLoader.cs:line 28
   at OpenUtau.Audio.AudioOutput..ctor() in /media/sf_Code/OpenUtau/OpenUtau.Core/Audio/AudioOutput.cs:line 36
   at OpenUtau.App.Program.InitAudio() in /media/sf_Code/OpenUtau/OpenUtau/Program.cs:line 67
   at OpenUtau.App.Program.Main(String[] args) in /media/sf_Code/OpenUtau/OpenUtau/Program.cs:line 28
[1]    63352 IOT instruction (core dumped)  ./OpenUtau-prerelease-x86_64.AppImage
```

**Expected behavior**
It should have launched the app

**Environment:**
 - OS: Pop!_OS 21.10 64-bit
 - Version v0.0.589
 - Voicebank used : None
 - Ust used : None

**Comment by stakira** [comment]
see https://github.com/stakira/OpenUtau/issues/124#issuecomment-1034489541
