### ISSUE TITLE
Open Utau does not install on Linux

### ISSUE THREAD

**Issue by Vector-frame** [stakira/OpenUtau#229]
**Describe the bug**

I recently uninstalled Ubuntu Studio 21.04 to install version 21.10 and when I went to install the app in App.image format, it didn't open. I tried to do it through the terminal and this warning appeared:

Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
   at OpenUtau.LibraryLoader.dlopen(String fileName, Int32 flags)
   at OpenUtau.LibraryLoader..ctor(String path, String library) in /media/sf_Code/OpenUtau/OpenUtau.Core/Util/LibraryLoader.cs:line 28
   at OpenUtau.Audio.AudioOutput..ctor() in /media/sf_Code/OpenUtau/OpenUtau.Core/Audio/AudioOutput.cs:line 36
   at OpenUtau.App.Program.InitAudio() in /media/sf_Code/OpenUtau/OpenUtau/Program.cs:line 67
   at OpenUtau.App.Program.Main(String[] args) in /media/sf_Code/OpenUtau/OpenUtau/Program.cs:line 28
Aborted (core dumped)

**Environment:**
 - OS: Linux (Ubuntu Studio)
 - Version [21.10]

**Comment by stakira** [comment]
see https://github.com/stakira/OpenUtau/issues/124#issuecomment-1034489541
