### ISSUE TITLE
Playback device button glitching

### ISSUE THREAD

**Issue by noahapaul** [stakira/OpenUtau#650]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

I have had this problem before. When I try to play a UST in OpenUTAU and the playback device isn't selected, I will select my Macbook speakers and it will work fine. But after I updated it, the dialog box to put my device does not pop up. It just remains the same as it was before. So, I effectively can not use OpenUTAU now.

### Explains how to reproduce the bug

Tools>Preferences>Playback Device>click dropdown menu, nothing happens.

### OS & Version

MacOS 13.1

### Logs

2023-04-11 15:31:52.324 -05:00 [INF] Logging initialized.
2023-04-11 15:31:52.458 -05:00 [INF] Unix 13.1.0
2023-04-11 15:31:52.461 -05:00 [INF] Darwin 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 X64 X64
2023-04-11 15:31:52.462 -05:00 [INF] OpenUtau v0.1.56.0 osx.13-x64
2023-04-11 15:31:52.463 -05:00 [INF] Data path = /Users/noahapaul/Library/OpenUtau
2023-04-11 15:31:52.463 -05:00 [INF] Cache path = /Users/noahapaul/Library/Caches/OpenUtau
2023-04-11 15:31:53.361 -05:00 [INF] Initializing application.
2023-04-11 15:31:53.881 -05:00 [INF] Initializing culture.
2023-04-11 15:31:53.886 -05:00 [INF] Initialized culture.
2023-04-11 15:31:53.886 -05:00 [INF] Initializing theme.
2023-04-11 15:31:53.918 -05:00 [INF] Initialized theme.
2023-04-11 15:31:53.918 -05:00 [INF] Initializing OpenUtau.
2023-04-11 15:31:53.926 -05:00 [INF] Searching singers.
2023-04-11 15:31:53.947 -05:00 [INF] Search all plugins: 00:00:00.0172003
2023-04-11 15:31:53.954 -05:00 [INF] Search all legacy plugins: 00:00:00.0058577
2023-04-11 15:31:53.958 -05:00 [INF] Initialized OpenUtau.
2023-04-11 15:31:53.958 -05:00 [INF] Initializing audio.
2023-04-11 15:31:53.960 -05:00 [INF] ReleaseSourceTemp /Users/noahapaul/Library/Caches/OpenUtau
2023-04-11 15:31:54.380 -05:00 [ERR] Failed to init PortAudio
System.DllNotFoundException: Unable to load shared library 'portaudio' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libportaudio, 0x0001): tried: 'libportaudio' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibportaudio' (no such file), '/usr/lib/libportaudio' (no such file, not in dyld cache), 'libportaudio' (no such file), '/usr/local/lib/libportaudio' (no such file), '/usr/lib/libportaudio' (no such file, not in dyld cache)
   at OpenUtau.Audio.PortAudioOutput..ctor() in /Users/appveyor/projects/openutau/OpenUtau.Core/Audio/PortAudioOutput.cs:line 35
   at OpenUtau.App.App.InitAudio() in /Users/appveyor/projects/openutau/OpenUtau/App.axaml.cs:line 101
2023-04-11 15:31:54.439 -05:00 [INF] Initialized audio.
2023-04-11 15:31:54.439 -05:00 [INF] Initialized application.
2023-04-11 15:31:54.506 -05:00 [INF] Framework initialization completed.
2023-04-11 15:31:54.682 -05:00 [INF] Creating main window.
2023-04-11 15:31:54.875 -05:00 [INF] Search all singers: 00:00:00.9485100
2023-04-11 15:31:55.080 -05:00 [INF] Initialized main window component.
2023-04-11 15:31:55.279 -05:00 [INF] Main window checking Update.
2023-04-11 15:31:55.282 -05:00 [INF] Created main window.
2023-04-11 15:31:55.839 -05:00 [INF] SchedulePreRender
2023-04-11 15:31:55.852 -05:00 [INF] Publish notification Load project
2023-04-11 15:31:55.966 -05:00 [INF] Domain https://github.com 00:00:00.6617437
2023-04-11 15:32:00.596 -05:00 [INF] 暗鳴ニュイ キレ音源 2/證鈴ｳｴ繝九Η繧､ 繧ｭ繝ｬ髻ｳ貅・ﾋ・ﾌ・鄭ﾌと男ﾆ停ｦﾆ辰 EnglishVCCV -DIVA-
2023-04-11 15:32:00.599 -05:00 [INF] 暗鳴ニュイ キレ音源 2/證鈴ｳｴ繝九Η繧､ 繧ｭ繝ｬ髻ｳ貅・ﾋ・ﾌ・鄭ﾌと男ﾆ停ｦﾆ辰 EnglishVCCV -DIVA-
2023-04-11 15:32:00.599 -05:00 [INF] 暗鳴ニュイ キレ音源 2/證鈴ｳｴ繝九Η繧､ 繧ｭ繝ｬ髻ｳ貅・ﾋ・ﾌ・鄭ﾌと男ﾆ停ｦﾆ辰 EnglishVCCV -DIVA-
2023-04-11 15:32:00.849 -05:00 [INF] SchedulePreRender
2023-04-11 15:32:01.024 -05:00 [ERR] Failed to connect domain https://hub.fastgit.xyz
System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at OpenUtau.App.ViewModels.UpdaterViewModel.ChooseDomainAsync() in /Users/appveyor/projects/openutau/OpenUtau/ViewModels/UpdaterViewModel.cs:line 67
2023-04-11 15:32:01.061 -05:00 [INF] Checking update at: https://github.com/stakira/OpenUtau/releases/latest/download/appcast.osx-x64.xml
2023-04-11 15:32:01.293 -05:00 [INF] Loaded /Users/noahapaul/Downloads/marco polo_INST + VSQ/marco polo_Inst.wav 00:00:00.6864005
2023-04-11 15:32:01.457 -05:00 [INF] Publish notification Load project
2023-04-11 15:32:01.753 -05:00 [INF] created bitmap 896, 120
2023-04-11 15:32:01.854 -05:00 [INF] Publish notification Phonemized
2023-04-11 15:32:01.870 -05:00 [INF] Publish notification Phonemized
2023-04-11 15:32:01.872 -05:00 [INF] Publish notification Phonemized
2023-04-11 15:32:02.274 -05:00 [INF] Built peaks /Users/noahapaul/Downloads/marco polo_INST + VSQ/marco polo_Inst.wav 00:00:00.9768728
2023-04-11 15:32:02.415 -05:00 [WRN] Validate Project not on main thread
2023-04-11 15:32:02.416 -05:00 [WRN] Pre-render notification. not on main thread
2023-04-11 15:32:02.423 -05:00 [INF] Publish notification Validate Project
2023-04-11 15:32:02.423 -05:00 [INF] SchedulePreRender
2023-04-11 15:32:02.423 -05:00 [INF] Publish notification Pre-render notification.
2023-04-11 15:32:02.459 -05:00 [WRN] Subword '/' from word '/' can't be found in the dictionary
2023-04-11 15:32:02.503 -05:00 [WRN] Subword '/' from word '/' can't be found in the dictionary
2023-04-11 15:32:02.533 -05:00 [WRN] Subword '/' from word '/' can't be found in the dictionary
2023-04-11 15:32:02.579 -05:00 [INF] Publish notification Phonemized
2023-04-11 15:32:02.587 -05:00 [INF] Publish notification Phonemized
2023-04-11 15:32:02.596 -05:00 [INF] Publish notification Phonemized
2023-04-11 15:32:02.870 -05:00 [INF] Publish notification Part rendered.
2023-04-11 15:32:02.994 -05:00 [INF] Publish notification Part rendered.
2023-04-11 15:32:03.138 -05:00 [INF] Publish notification Part rendered.
2023-04-11 15:32:05.665 -05:00 [INF] StartPlayback at 00:00:00.7317073
2023-04-11 15:32:06.016 -05:00 [INF] Publish notification Part rendered.
2023-04-11 15:32:06.020 -05:00 [INF] Publish notification Part rendered.
2023-04-11 15:32:06.034 -05:00 [INF] Publish notification Part rendered.
2023-04-11 15:32:25.279 -05:00 [INF] Autosave skipped.
2023-04-11 15:32:33.992 -05:00 [INF] StartPlayback at 00:00:00.7317073
2023-04-11 15:32:34.430 -05:00 [INF] Publish notification Part rendered.
2023-04-11 15:32:34.436 -05:00 [INF] Publish notification Part rendered.
2023-04-11 15:32:34.450 -05:00 [INF] Publish notification Part rendered.
2023-04-11 15:32:37.740 -05:00 [INF] Checking update at: https://github.com/stakira/OpenUtau/releases/latest/download/appcast.osx-x64.xml
2023-04-11 15:32:55.281 -05:00 [INF] Autosave skipped.
2023-04-11 15:33:25.278 -05:00 [INF] Autosave skipped.
2023-04-11 15:33:55.276 -05:00 [INF] Autosave skipped.
2023-04-11 15:34:25.275 -05:00 [INF] Autosave skipped.
2023-04-11 15:34:55.274 -05:00 [INF] Autosave skipped.
2023-04-11 15:35:25.273 -05:00 [INF] Autosave skipped.
2023-04-11 15:35:55.272 -05:00 [INF] Autosave skipped.
2023-04-11 15:36:25.273 -05:00 [INF] Autosave skipped.
2023-04-11 15:36:55.271 -05:00 [INF] Autosave skipped.
2023-04-11 15:37:25.270 -05:00 [INF] Autosave skipped.

**Comment by alex9505** [comment]
It seems OpenUtau cant find the "portaudio.dll" file.

This file should be located in the OpenUtau installation folder.
