### ISSUE TITLE
Linux - App will not open after changing locale to ja_JP.UTF8

### ISSUE THREAD

**Issue by TELEK1NET1C** [stakira/OpenUtau#755]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

i have changed my locale from from en_US.UTF8 to ja_JP.UTF8 with both my desktop environment and locale.gen, and after a reboot, OpenUTAU will not open. it seems to begin to load, and then crash. 

i have manually gone into prefs.json and changed the language to ja-JP, and it still does not open, and i have uninstalled and reinstalled the program using yay.

it seems to be font-related.

### Explains how to reproduce the bug

1. install openutau-installer using yay in the en-US.UTF8 locale, and then open it once.
2. change the locale to ja_JP.UTF8 and reboot.
3. try to open OpenUTAU, and it will load and then crash.

### OS & Version

Arch Linux 6.3.2

### Logs

[log20230624.txt](https://github.com/stakira/OpenUtau/files/11855571/log20230624.txt)

**Comment by TELEK1NET1C** [comment]
update: changing back to en_US.UTF8 fixes the problem, but i would still look into this issue just in case. i am leaving the issue open for this reason. i'm willing to go back to ja_JP.UTF8 to help with troubleshooting!

**Comment by computorcat** [comment]
also had this issue on debian 11!  seems to be an unhandled exception.
````2023-07-14 11:14:27.359 +01:00 [ERR] Unhandled exception
System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl) in /_/src/Avalonia.Base/Media/FontManager.cs:line 37
   at Avalonia.Media.FontManager.get_Current() in /_/src/Avalonia.Base/Media/FontManager.cs:line 59
   at Avalonia.Media.Typeface.get_GlyphTypeface() in /_/src/Avalonia.Base/Media/Typeface.cs:line 87
   at Avalonia.Rendering.Composition.Compositor.get_DiagnosticTextRenderer() in /_/src/Avalonia.Base/Rendering/Composition/Compositor.cs:line 58
   at Avalonia.Rendering.Composition.Compositor.CreateCompositionTarget(Func`1 surfaces) in /_/src/Avalonia.Base/Rendering/Composition/Compositor.Factories.cs:line 17
   at Avalonia.Rendering.Composition.CompositingRenderer..ctor(IRenderRoot root, Compositor compositor, Func`1 surfaces) in /_/src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs:line 53
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver) in /_/src/Avalonia.Controls/TopLevel.cs:line 188
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver) in /_/src/Avalonia.Controls/WindowBase.cs:line 55
   at Avalonia.Controls.Window..ctor(IWindowImpl impl) in /_/src/Avalonia.Controls/Window.cs:line 223
   at Avalonia.Controls.Window..ctor() in /_/src/Avalonia.Controls/Window.cs:line 214
   at OpenUtau.App.Views.MainWindow..ctor() in /home/appveyor/projects/openutau/OpenUtau/Views/MainWindow.axaml.cs:line 45
   at OpenUtau.App.App.OnFrameworkInitializationCompleted() in /home/appveyor/projects/openutau/OpenUtau/App.axaml.cs:line 34
   at Avalonia.AppBuilder.SetupUnsafe() in /_/src/Avalonia.Controls/AppBuilder.cs:line 307
   at Avalonia.AppBuilder.Setup() in /_/src/Avalonia.Controls/AppBuilder.cs:line 291
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 219
   at OpenUtau.App.Program.Main(String[] args) in /home/appveyor/projects/openutau/OpenUtau/Program.cs:line 41```
