### ISSUE TITLE
Crash while moving notes

### ISSUE THREAD

**Issue by 20kdc** [stakira/OpenUtau#796]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

I repeatedly get crashes (in the form of exceptions, see logs) while moving notes. These seem to occur semi-randomly.

### Explains how to reproduce the bug

Occurs when moving notes.
In the event that it might be tied to BPM/time signature, the BPM/time signature is 4/4 172bpm.
I'm not able to figure out which notes cause the issue or why.
The problem is not "sticky" to a note either; after a crash, the note is safe to move.
(Project file not attached because I was messing around with covering a song. Sorry!)

### OS & Version

Ubuntu 22.04.2 LTS (Jammy Jellyfish) ; OpenUtau 0.1.158 official Linux build

### Logs

```
Unhandled exception. System.ArgumentException: '0' cannot be greater than -1440.
   at System.Math.ThrowMinMaxException[T](T min, T max)
   at OpenUtau.App.Views.NoteMoveEditState.Update(IPointer pointer, Point point) in /home/appveyor/projects/openutau/OpenUtau/Views/NoteEditStates.cs:line 194
   at OpenUtau.App.Views.PianoRollWindow.NotesCanvasPointerMoved(Object sender, PointerEventArgs args) in /home/appveyor/projects/openutau/OpenUtau/Views/PianoRollWindow.axaml.cs:line 483
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 118
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/Interactive.cs:line 126
   at Avalonia.Input.MouseDevice.MouseMove(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties properties, KeyModifiers inputModifiers, Lazy`1 intermediatePoints, IInputElement hitTest) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 164
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 58
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Base/Input/InputManager.cs:line 37
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 739
   at Avalonia.X11.X11Window.DispatchInput(RawInputEventArgs args) in /_/src/Avalonia.X11/X11Window.cs:line 747
   at Avalonia.RawEventGrouper.Dispatch(RawInputEventArgs ev) in /_/src/Shared/RawEventGrouping.cs:line 127
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 197
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl) in /_/src/Avalonia.Base/Threading/DispatcherFrame.cs:line 117
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 53
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 80
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 127
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 220
   at OpenUtau.App.Program.Main(String[] args) in /home/appveyor/projects/openutau/OpenUtau/Program.cs:line 41
Aborted
```
[log20230802.txt](https://github.com/stakira/OpenUtau/files/12242205/log20230802.txt)

**Comment by lottev1991** [comment]
I'm also noticing this in your log:
```
2023-08-02 15:56:24.078 +01:00 [ERR] phonemizer error a
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at OpenUtau.Plugin.Builtin.EnglishVCCVPhonemizer.ProcessSyllable(Syllable syllable) in /home/appveyor/projects/openutau/OpenUtau.Plugin.Builtin/EnglishVCCVPhonemizer.cs:line 118
   at OpenUtau.Plugin.Builtin.SyllableBasedPhonemizer.Process(Note[] notes, Nullable`1 prev, Nullable`1 next, Nullable`1 prevNeighbour, Nullable`1 nextNeighbour, Note[] prevNeighbours) in /home/appveyor/projects/openutau/OpenUtau.Plugin.Builtin/SyllableBasedPhonemizer.cs:line 135
   at OpenUtau.Api.PhonemizerRunner.Phonemize(PhonemizerRequest request) in /home/appveyor/projects/openutau/OpenUtau.Core/Api/PhonemizerRunner.cs:line 168
```
Have you been experiencing issues with this as well?

**Comment by 20kdc** [comment]
I didn't run into issues with phonemization, at least outside of figuring out a blend between what the lyrics, the phonemizer and the voice will accept, but that's more just due to me not really picking the right singer for the task
