### ISSUE TITLE
Trying to play a UST causes a crash

### ISSUE THREAD

**Issue by Lightzaver** [stakira/OpenUtau#8]
When I try to play a UST/Midi/VSQ or render a file, OpenUtau crashes without any error. I've tried using an external resampler too but the same happens.

I ran it with the debugger and this was the error I got.
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: path1
  Source=mscorlib
  StackTrace:
   at System.IO.Path.Combine(String path1, String path2)
   at OpenUtau.Core.PathManager.GetCachePath(String filepath) in C:\Users\cjscs\Documents\GitHub\OpenUtau\OpenUtau\Core\Util\PathManager.cs:line 87
   at OpenUtau.Core.Render.ResamplerInterface.RenderAsync(UVoicePart part, UProject project, IResamplerDriver engine, BackgroundWorker worker) in C:\Users\cjscs\Documents\GitHub\OpenUtau\OpenUtau\Core\Render\ResamplerInterface.cs:line 61
   at OpenUtau.Core.Render.ResamplerInterface.worker_DoWork(Object sender, DoWorkEventArgs e) in C:\Users\cjscs\Documents\GitHub\OpenUtau\OpenUtau\Core\Render\ResamplerInterface.cs:line 41
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

I tried saving the file then trying to play it and got a different error through the debugger.
```
System.ArgumentException
  HResult=0x80070057
  Message=Must provide at least one input in this constructor
  Source=OpenUtau
  StackTrace:
   at OpenUtau.Core.Render.SequencingSampleProvider..ctor(IEnumerable`1 sources) in C:\Users\cjscs\Documents\GitHub\OpenUtau\OpenUtau\Core\Render\NAudio\SequencingSampleProvider.cs:line 36
   at OpenUtau.Core.Render.ResamplerInterface.worker_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\Users\cjscs\Documents\GitHub\OpenUtau\OpenUtau\Core\Render\ResamplerInterface.cs:line 50
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at OpenUtau.App.Main() in C:\Users\cjscs\Documents\GitHub\OpenUtau\OpenUtau\App.xaml.cs:line 32
```

**Comment by stakira** [comment]
Might be because there is no resampler. Had some update to make it clear.

**Comment by Lightzaver** [comment]
Still crashes sadly. Using the default resampler placed in the resampler folder. I got this error from the debugger:
```
[Exception_131956689310014724.zip](https://github.com/stakira/OpenUtau/files/2906315/Exception_131956689310014724.zip)

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=An exception occurred during the operation, making the result invalid.  Check InnerException for exception details.
  Source=System
  StackTrace:
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at OpenUtau.Core.Render.ResamplerInterface.worker_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at OpenUtau.App.Main()

Inner Exception 1:
ArgumentNullException: Value cannot be null.
```

**Comment by stakira** [comment]
At the moment OpenUtau does not come with a resampler. Could you try a third party resampler? Thanks.

**Comment by Lightzaver** [comment]
I've tried with fresampler and vs4u and the same error.
[Exception_131957634489766215.zip](https://github.com/stakira/OpenUtau/files/2911586/Exception_131957634489766215.zip)

**Comment by Lightzaver** [comment]
If it helps, I'm now getting
```
System.ArgumentException: 'Must provide at least one input in this constructor'
```
from the 'if (this.sources.Count == 0)' in SequencingSampleProvider, but I'm not sure what I would have to change to make this not happen.

**Comment by stakira** [comment]
Thanks for reporting. I saw that one too. The cause is no sounds is resampled at all due to not being able to find samples in sound lib for notes. I'll fix the crash. We still need to figure out why it doesn't resample. UI needs some work to make it clear to user too.
