### ISSUE TITLE
EN Phonemizers Not Working

### ISSUE THREAD

**Issue by YstLol** [stakira/OpenUtau#910]
### Acknowledgement

- [x] I have read Getting-Started and FAQ

### 🐛 Describe the bug

OpenUTAU gives "error" as a phoneme whenever I try to use english phonemizers. I tried all of them on Teto EN.

### Explains how to reproduce the bug

All EN VBs with EN phonemizers, or EN to JA phonemizer with JP VBs.

### OS & Version

Windows 7

### Logs

2023-10-28 14:19:14.918 +03:00 [INF] ExecuteCmd Change notes lyric
2023-10-28 14:19:14.918 +03:00 [INF] undoGroup ended
2023-10-28 14:19:14.918 +03:00 [INF] SchedulePreRender
2023-10-28 14:19:14.918 +03:00 [INF] Publish notification Pre-render notification.
2023-10-28 14:19:14.921 +03:00 [INF] Publish notification Phonemized
2023-10-28 14:19:20.499 +03:00 [INF] undoGroup started
2023-10-28 14:19:20.501 +03:00 [INF] ExecuteCmd Change phonemizer
2023-10-28 14:19:20.501 +03:00 [INF] undoGroup ended
2023-10-28 14:19:20.501 +03:00 [INF] SchedulePreRender
2023-10-28 14:19:20.502 +03:00 [INF] Publish notification Pre-render notification.
2023-10-28 14:19:20.520 +03:00 [WRN] Validate Project not on main thread
2023-10-28 14:19:20.521 +03:00 [WRN] Pre-render notification. not on main thread
2023-10-28 14:19:20.522 +03:00 [INF] Publish notification Phonemized
2023-10-28 14:19:20.524 +03:00 [INF] Publish notification Validate Project
2023-10-28 14:19:20.524 +03:00 [INF] SchedulePreRender
2023-10-28 14:19:20.525 +03:00 [INF] Publish notification Pre-render notification.
2023-10-28 14:19:20.534 +03:00 [ERR] phonemizer error hey
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenUtau.Api.G2pPack.Query(String grapheme) in C:\projects\openutau\OpenUtau.Core\Api\G2pPack.cs:line 74
   at OpenUtau.Api.G2pFallbacks.Query(String grapheme) in C:\projects\openutau\OpenUtau.Core\Api\G2pFallbacks.cs:line 29
   at OpenUtau.Api.G2pRemapper.Query(String grapheme) in C:\projects\openutau\OpenUtau.Core\Api\G2pRemapper.cs:line 27
   at OpenUtau.Plugin.Builtin.SyllableBasedPhonemizer.GetSymbols(Note note) in C:\projects\openutau\OpenUtau.Plugin.Builtin\SyllableBasedPhonemizer.cs:line 262
   at OpenUtau.Plugin.Builtin.ENDeltaPhonemizer.GetSymbols(Note note) in C:\projects\openutau\OpenUtau.Plugin.Builtin\ENDeltaPhonemizer.cs:line 68
   at OpenUtau.Plugin.Builtin.SyllableBasedPhonemizer.GetSymbolsAndVowels(Note[] notes) in C:\projects\openutau\OpenUtau.Plugin.Builtin\SyllableBasedPhonemizer.cs:line 393
   at OpenUtau.Plugin.Builtin.SyllableBasedPhonemizer.MakeSyllables(Note[] inputNotes, Nullable`1 prevEnding) in C:\projects\openutau\OpenUtau.Plugin.Builtin\SyllableBasedPhonemizer.cs:line 292
   at OpenUtau.Plugin.Builtin.SyllableBasedPhonemizer.Process(Note[] notes, Nullable`1 prev, Nullable`1 next, Nullable`1 prevNeighbour, Nullable`1 nextNeighbour, Note[] prevNeighbours) in C:\projects\openutau\OpenUtau.Plugin.Builtin\SyllableBasedPhonemizer.cs:line 144
   at OpenUtau.Api.PhonemizerRunner.Phonemize(PhonemizerRequest request) in C:\projects\openutau\OpenUtau.Core\Api\PhonemizerRunner.cs:line 168
2023-10-28 14:19:20.536 +03:00 [INF] Publish notification Phonemized
2023-10-28 14:19:22.746 +03:00 [INF] undoGroup started
2023-10-28 14:19:22.746 +03:00 [INF] ExecuteCmd Change phonemizer
2023-10-28 14:19:22.747 +03:00 [INF] undoGroup ended
2023-10-28 14:19:22.747 +03:00 [INF] SchedulePreRender
2023-10-28 14:19:22.747 +03:00 [INF] Publish notification Pre-render notification.
2023-10-28 14:19:22.752 +03:00 [WRN] Validate Project not on main thread
2023-10-28 14:19:22.752 +03:00 [WRN] Pre-render notification. not on main thread
2023-10-28 14:19:22.762 +03:00 [INF] Publish notification Phonemized
2023-10-28 14:19:22.765 +03:00 [INF] Publish notification Validate Project
2023-10-28 14:19:22.765 +03:00 [INF] SchedulePreRender
2023-10-28 14:19:22.765 +03:00 [INF] Publish notification Pre-render notification.
2023-10-28 14:19:22.766 +03:00 [ERR] phonemizer error hey
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenUtau.Api.G2pPack.Query(String grapheme) in C:\projects\openutau\OpenUtau.Core\Api\G2pPack.cs:line 74
   at OpenUtau.Api.G2pRemapper.Query(String grapheme) in C:\projects\openutau\OpenUtau.Core\Api\G2pRemapper.cs:line 27
   at OpenUtau.Plugin.Builtin.SyllableBasedPhonemizer.GetSymbols(Note note) in C:\projects\openutau\OpenUtau.Plugin.Builtin\SyllableBasedPhonemizer.cs:line 262
   at OpenUtau.Plugin.Builtin.ENtoJAPhonemizer.GetSymbols(Note note) in C:\projects\openutau\OpenUtau.Plugin.Builtin\ENtoJAPhonemizer.cs:line 209
   at OpenUtau.Plugin.Builtin.SyllableBasedPhonemizer.GetSymbolsAndVowels(Note[] notes) in C:\projects\openutau\OpenUtau.Plugin.Builtin\SyllableBasedPhonemizer.cs:line 393
   at OpenUtau.Plugin.Builtin.SyllableBasedPhonemizer.MakeSyllables(Note[] inputNotes, Nullable`1 prevEnding) in C:\projects\openutau\OpenUtau.Plugin.Builtin\SyllableBasedPhonemizer.cs:line 292
   at OpenUtau.Plugin.Builtin.SyllableBasedPhonemizer.Process(Note[] notes, Nullable`1 prev, Nullable`1 next, Nullable`1 prevNeighbour, Nullable`1 nextNeighbour, Note[] prevNeighbours) in C:\projects\openutau\OpenUtau.Plugin.Builtin\SyllableBasedPhonemizer.cs:line 144
   at OpenUtau.Api.PhonemizerRunner.Phonemize(PhonemizerRequest request) in C:\projects\openutau\OpenUtau.Core\Api\PhonemizerRunner.cs:line 168
2023-10-28 14:19:22.768 +03:00 [INF] Publish notification Phonemized
2023-10-28 14:19:24.279 +03:00 [INF] undoGroup started
2023-10-28 14:19:24.280 +03:00 [INF] ExecuteCmd Change phonemizer
2023-10-28 14:19:24.280 +03:00 [INF] undoGroup ended
2023-10-28 14:19:24.280 +03:00 [INF] SchedulePreRender
2023-10-28 14:19:24.281 +03:00 [INF] Publish notification Pre-render notification.
2023-10-28 14:19:24.302 +03:00 [INF] Publish notification Phonemized
2023-10-28 14:19:25.645 +03:00 [INF] undoGroup started
2023-10-28 14:19:25.646 +03:00 [INF] ExecuteCmd Change phonemizer
2023-10-28 14:19:25.646 +03:00 [INF] undoGroup ended
2023-10-28 14:19:25.646 +03:00 [INF] SchedulePreRender
2023-10-28 14:19:25.647 +03:00 [INF] Publish notification Pre-render notification.
2023-10-28 14:19:25.660 +03:00 [INF] Publish notification Phonemized
2023-10-28 14:19:29.700 +03:00 [INF] Exiting.

**Comment by lottev1991** [comment]
The G2P-based phonemizers are not supported on Windows 7. Moreover, Windows 7 is no longer officially supported by Microsoft and has glaring security issues as a result. I strongly suggest you upgrade.
